// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AnalyticsMultisigTxsBySafeResponse analytics multisig txs by safe response
//
// swagger:model AnalyticsMultisigTxsBySafeResponse
type AnalyticsMultisigTxsBySafeResponse struct {

	// Master copy
	// Required: true
	MasterCopy *string `json:"masterCopy"`

	// Safe
	// Required: true
	Safe *string `json:"safe"`

	// Transactions
	// Required: true
	Transactions *int64 `json:"transactions"`
}

// Validate validates this analytics multisig txs by safe response
func (m *AnalyticsMultisigTxsBySafeResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMasterCopy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSafe(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTransactions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AnalyticsMultisigTxsBySafeResponse) validateMasterCopy(formats strfmt.Registry) error {

	if err := validate.Required("masterCopy", "body", m.MasterCopy); err != nil {
		return err
	}

	return nil
}

func (m *AnalyticsMultisigTxsBySafeResponse) validateSafe(formats strfmt.Registry) error {

	if err := validate.Required("safe", "body", m.Safe); err != nil {
		return err
	}

	return nil
}

func (m *AnalyticsMultisigTxsBySafeResponse) validateTransactions(formats strfmt.Registry) error {

	if err := validate.Required("transactions", "body", m.Transactions); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this analytics multisig txs by safe response based on context it is used
func (m *AnalyticsMultisigTxsBySafeResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AnalyticsMultisigTxsBySafeResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AnalyticsMultisigTxsBySafeResponse) UnmarshalBinary(b []byte) error {
	var res AnalyticsMultisigTxsBySafeResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
