// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FirebaseDevice firebase device
//
// swagger:model FirebaseDevice
type FirebaseDevice struct {

	// Build number
	// Required: true
	// Minimum: 0
	BuildNumber *int64 `json:"buildNumber"`

	// Bundle
	// Required: true
	// Max Length: 100
	// Min Length: 1
	Bundle *string `json:"bundle"`

	// Cloud messaging token
	// Required: true
	// Max Length: 200
	// Min Length: 100
	CloudMessagingToken *string `json:"cloudMessagingToken"`

	// Device type
	// Required: true
	// Enum: [ANDROID IOS WEB]
	DeviceType *string `json:"deviceType"`

	// safes
	// Required: true
	Safes []string `json:"safes"`

	// signatures
	Signatures []string `json:"signatures"`

	// Timestamp
	Timestamp int64 `json:"timestamp,omitempty"`

	// Uuid
	// Format: uuid
	UUID *strfmt.UUID `json:"uuid,omitempty"`

	// Version
	// Required: true
	// Max Length: 100
	// Min Length: 1
	Version *string `json:"version"`
}

// Validate validates this firebase device
func (m *FirebaseDevice) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBuildNumber(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBundle(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCloudMessagingToken(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeviceType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSafes(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUUID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FirebaseDevice) validateBuildNumber(formats strfmt.Registry) error {

	if err := validate.Required("buildNumber", "body", m.BuildNumber); err != nil {
		return err
	}

	if err := validate.MinimumInt("buildNumber", "body", *m.BuildNumber, 0, false); err != nil {
		return err
	}

	return nil
}

func (m *FirebaseDevice) validateBundle(formats strfmt.Registry) error {

	if err := validate.Required("bundle", "body", m.Bundle); err != nil {
		return err
	}

	if err := validate.MinLength("bundle", "body", *m.Bundle, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("bundle", "body", *m.Bundle, 100); err != nil {
		return err
	}

	return nil
}

func (m *FirebaseDevice) validateCloudMessagingToken(formats strfmt.Registry) error {

	if err := validate.Required("cloudMessagingToken", "body", m.CloudMessagingToken); err != nil {
		return err
	}

	if err := validate.MinLength("cloudMessagingToken", "body", *m.CloudMessagingToken, 100); err != nil {
		return err
	}

	if err := validate.MaxLength("cloudMessagingToken", "body", *m.CloudMessagingToken, 200); err != nil {
		return err
	}

	return nil
}

var firebaseDeviceTypeDeviceTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ANDROID","IOS","WEB"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		firebaseDeviceTypeDeviceTypePropEnum = append(firebaseDeviceTypeDeviceTypePropEnum, v)
	}
}

const (

	// FirebaseDeviceDeviceTypeANDROID captures enum value "ANDROID"
	FirebaseDeviceDeviceTypeANDROID string = "ANDROID"

	// FirebaseDeviceDeviceTypeIOS captures enum value "IOS"
	FirebaseDeviceDeviceTypeIOS string = "IOS"

	// FirebaseDeviceDeviceTypeWEB captures enum value "WEB"
	FirebaseDeviceDeviceTypeWEB string = "WEB"
)

// prop value enum
func (m *FirebaseDevice) validateDeviceTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, firebaseDeviceTypeDeviceTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *FirebaseDevice) validateDeviceType(formats strfmt.Registry) error {

	if err := validate.Required("deviceType", "body", m.DeviceType); err != nil {
		return err
	}

	// value enum
	if err := m.validateDeviceTypeEnum("deviceType", "body", *m.DeviceType); err != nil {
		return err
	}

	return nil
}

func (m *FirebaseDevice) validateSafes(formats strfmt.Registry) error {

	if err := validate.Required("safes", "body", m.Safes); err != nil {
		return err
	}

	return nil
}

func (m *FirebaseDevice) validateUUID(formats strfmt.Registry) error {
	if swag.IsZero(m.UUID) { // not required
		return nil
	}

	if err := validate.FormatOf("uuid", "body", "uuid", m.UUID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *FirebaseDevice) validateVersion(formats strfmt.Registry) error {

	if err := validate.Required("version", "body", m.Version); err != nil {
		return err
	}

	if err := validate.MinLength("version", "body", *m.Version, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("version", "body", *m.Version, 100); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this firebase device based on context it is used
func (m *FirebaseDevice) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FirebaseDevice) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FirebaseDevice) UnmarshalBinary(b []byte) error {
	var res FirebaseDevice
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
