// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SafeDelegateDelete safe delegate delete
//
// swagger:model SafeDelegateDelete
type SafeDelegateDelete struct {

	// Delegate
	// Required: true
	Delegate *string `json:"delegate"`

	// Safe
	// Required: true
	Safe *string `json:"safe"`

	// Signature
	// Required: true
	Signature *string `json:"signature"`
}

// Validate validates this safe delegate delete
func (m *SafeDelegateDelete) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDelegate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSafe(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSignature(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SafeDelegateDelete) validateDelegate(formats strfmt.Registry) error {

	if err := validate.Required("delegate", "body", m.Delegate); err != nil {
		return err
	}

	return nil
}

func (m *SafeDelegateDelete) validateSafe(formats strfmt.Registry) error {

	if err := validate.Required("safe", "body", m.Safe); err != nil {
		return err
	}

	return nil
}

func (m *SafeDelegateDelete) validateSignature(formats strfmt.Registry) error {

	if err := validate.Required("signature", "body", m.Signature); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this safe delegate delete based on context it is used
func (m *SafeDelegateDelete) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SafeDelegateDelete) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SafeDelegateDelete) UnmarshalBinary(b []byte) error {
	var res SafeDelegateDelete
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
