// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SafeMultisigTransactionEstimateResponse safe multisig transaction estimate response
//
// swagger:model SafeMultisigTransactionEstimateResponse
type SafeMultisigTransactionEstimateResponse struct {

	// Safe tx gas
	// Required: true
	// Min Length: 1
	SafeTxGas *string `json:"safeTxGas"`
}

// Validate validates this safe multisig transaction estimate response
func (m *SafeMultisigTransactionEstimateResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSafeTxGas(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SafeMultisigTransactionEstimateResponse) validateSafeTxGas(formats strfmt.Registry) error {

	if err := validate.Required("safeTxGas", "body", m.SafeTxGas); err != nil {
		return err
	}

	if err := validate.MinLength("safeTxGas", "body", *m.SafeTxGas, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this safe multisig transaction estimate response based on context it is used
func (m *SafeMultisigTransactionEstimateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SafeMultisigTransactionEstimateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SafeMultisigTransactionEstimateResponse) UnmarshalBinary(b []byte) error {
	var res SafeMultisigTransactionEstimateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
