// Code generated by go-swagger; DO NOT EDIT.

package safes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewSafesTransfersListParams creates a new SafesTransfersListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSafesTransfersListParams() *SafesTransfersListParams {
	return &SafesTransfersListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSafesTransfersListParamsWithTimeout creates a new SafesTransfersListParams object
// with the ability to set a timeout on a request.
func NewSafesTransfersListParamsWithTimeout(timeout time.Duration) *SafesTransfersListParams {
	return &SafesTransfersListParams{
		timeout: timeout,
	}
}

// NewSafesTransfersListParamsWithContext creates a new SafesTransfersListParams object
// with the ability to set a context for a request.
func NewSafesTransfersListParamsWithContext(ctx context.Context) *SafesTransfersListParams {
	return &SafesTransfersListParams{
		Context: ctx,
	}
}

// NewSafesTransfersListParamsWithHTTPClient creates a new SafesTransfersListParams object
// with the ability to set a custom HTTPClient for a request.
func NewSafesTransfersListParamsWithHTTPClient(client *http.Client) *SafesTransfersListParams {
	return &SafesTransfersListParams{
		HTTPClient: client,
	}
}

/* SafesTransfersListParams contains all the parameters to send to the API endpoint
   for the safes transfers list operation.

   Typically these are written to a http.Request.
*/
type SafesTransfersListParams struct {

	// From.
	From *string

	// Address.
	Address string

	// BlockNumber.
	BlockNumber *float64

	// BlockNumberGt.
	BlockNumberGt *float64

	// BlockNumberLt.
	BlockNumberLt *float64

	// Erc20.
	Erc20 *string

	// Erc721.
	Erc721 *string

	// Ether.
	Ether *string

	// ExecutionDateGt.
	ExecutionDateGt *string

	// ExecutionDateGte.
	ExecutionDateGte *string

	// ExecutionDateLt.
	ExecutionDateLt *string

	// ExecutionDateLte.
	ExecutionDateLte *string

	/* Limit.

	   Number of results to return per page.
	*/
	Limit *int64

	/* Offset.

	   The initial index from which to return the results.
	*/
	Offset *int64

	// To.
	To *string

	// TokenAddress.
	TokenAddress *string

	// TransactionHash.
	TransactionHash *string

	// Value.
	Value *float64

	// ValueGt.
	ValueGt *float64

	// ValueLt.
	ValueLt *float64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the safes transfers list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SafesTransfersListParams) WithDefaults() *SafesTransfersListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the safes transfers list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SafesTransfersListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the safes transfers list params
func (o *SafesTransfersListParams) WithTimeout(timeout time.Duration) *SafesTransfersListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the safes transfers list params
func (o *SafesTransfersListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the safes transfers list params
func (o *SafesTransfersListParams) WithContext(ctx context.Context) *SafesTransfersListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the safes transfers list params
func (o *SafesTransfersListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the safes transfers list params
func (o *SafesTransfersListParams) WithHTTPClient(client *http.Client) *SafesTransfersListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the safes transfers list params
func (o *SafesTransfersListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFrom adds the from to the safes transfers list params
func (o *SafesTransfersListParams) WithFrom(from *string) *SafesTransfersListParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the safes transfers list params
func (o *SafesTransfersListParams) SetFrom(from *string) {
	o.From = from
}

// WithAddress adds the address to the safes transfers list params
func (o *SafesTransfersListParams) WithAddress(address string) *SafesTransfersListParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the safes transfers list params
func (o *SafesTransfersListParams) SetAddress(address string) {
	o.Address = address
}

// WithBlockNumber adds the blockNumber to the safes transfers list params
func (o *SafesTransfersListParams) WithBlockNumber(blockNumber *float64) *SafesTransfersListParams {
	o.SetBlockNumber(blockNumber)
	return o
}

// SetBlockNumber adds the blockNumber to the safes transfers list params
func (o *SafesTransfersListParams) SetBlockNumber(blockNumber *float64) {
	o.BlockNumber = blockNumber
}

// WithBlockNumberGt adds the blockNumberGt to the safes transfers list params
func (o *SafesTransfersListParams) WithBlockNumberGt(blockNumberGt *float64) *SafesTransfersListParams {
	o.SetBlockNumberGt(blockNumberGt)
	return o
}

// SetBlockNumberGt adds the blockNumberGt to the safes transfers list params
func (o *SafesTransfersListParams) SetBlockNumberGt(blockNumberGt *float64) {
	o.BlockNumberGt = blockNumberGt
}

// WithBlockNumberLt adds the blockNumberLt to the safes transfers list params
func (o *SafesTransfersListParams) WithBlockNumberLt(blockNumberLt *float64) *SafesTransfersListParams {
	o.SetBlockNumberLt(blockNumberLt)
	return o
}

// SetBlockNumberLt adds the blockNumberLt to the safes transfers list params
func (o *SafesTransfersListParams) SetBlockNumberLt(blockNumberLt *float64) {
	o.BlockNumberLt = blockNumberLt
}

// WithErc20 adds the erc20 to the safes transfers list params
func (o *SafesTransfersListParams) WithErc20(erc20 *string) *SafesTransfersListParams {
	o.SetErc20(erc20)
	return o
}

// SetErc20 adds the erc20 to the safes transfers list params
func (o *SafesTransfersListParams) SetErc20(erc20 *string) {
	o.Erc20 = erc20
}

// WithErc721 adds the erc721 to the safes transfers list params
func (o *SafesTransfersListParams) WithErc721(erc721 *string) *SafesTransfersListParams {
	o.SetErc721(erc721)
	return o
}

// SetErc721 adds the erc721 to the safes transfers list params
func (o *SafesTransfersListParams) SetErc721(erc721 *string) {
	o.Erc721 = erc721
}

// WithEther adds the ether to the safes transfers list params
func (o *SafesTransfersListParams) WithEther(ether *string) *SafesTransfersListParams {
	o.SetEther(ether)
	return o
}

// SetEther adds the ether to the safes transfers list params
func (o *SafesTransfersListParams) SetEther(ether *string) {
	o.Ether = ether
}

// WithExecutionDateGt adds the executionDateGt to the safes transfers list params
func (o *SafesTransfersListParams) WithExecutionDateGt(executionDateGt *string) *SafesTransfersListParams {
	o.SetExecutionDateGt(executionDateGt)
	return o
}

// SetExecutionDateGt adds the executionDateGt to the safes transfers list params
func (o *SafesTransfersListParams) SetExecutionDateGt(executionDateGt *string) {
	o.ExecutionDateGt = executionDateGt
}

// WithExecutionDateGte adds the executionDateGte to the safes transfers list params
func (o *SafesTransfersListParams) WithExecutionDateGte(executionDateGte *string) *SafesTransfersListParams {
	o.SetExecutionDateGte(executionDateGte)
	return o
}

// SetExecutionDateGte adds the executionDateGte to the safes transfers list params
func (o *SafesTransfersListParams) SetExecutionDateGte(executionDateGte *string) {
	o.ExecutionDateGte = executionDateGte
}

// WithExecutionDateLt adds the executionDateLt to the safes transfers list params
func (o *SafesTransfersListParams) WithExecutionDateLt(executionDateLt *string) *SafesTransfersListParams {
	o.SetExecutionDateLt(executionDateLt)
	return o
}

// SetExecutionDateLt adds the executionDateLt to the safes transfers list params
func (o *SafesTransfersListParams) SetExecutionDateLt(executionDateLt *string) {
	o.ExecutionDateLt = executionDateLt
}

// WithExecutionDateLte adds the executionDateLte to the safes transfers list params
func (o *SafesTransfersListParams) WithExecutionDateLte(executionDateLte *string) *SafesTransfersListParams {
	o.SetExecutionDateLte(executionDateLte)
	return o
}

// SetExecutionDateLte adds the executionDateLte to the safes transfers list params
func (o *SafesTransfersListParams) SetExecutionDateLte(executionDateLte *string) {
	o.ExecutionDateLte = executionDateLte
}

// WithLimit adds the limit to the safes transfers list params
func (o *SafesTransfersListParams) WithLimit(limit *int64) *SafesTransfersListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the safes transfers list params
func (o *SafesTransfersListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the safes transfers list params
func (o *SafesTransfersListParams) WithOffset(offset *int64) *SafesTransfersListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the safes transfers list params
func (o *SafesTransfersListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithTo adds the to to the safes transfers list params
func (o *SafesTransfersListParams) WithTo(to *string) *SafesTransfersListParams {
	o.SetTo(to)
	return o
}

// SetTo adds the to to the safes transfers list params
func (o *SafesTransfersListParams) SetTo(to *string) {
	o.To = to
}

// WithTokenAddress adds the tokenAddress to the safes transfers list params
func (o *SafesTransfersListParams) WithTokenAddress(tokenAddress *string) *SafesTransfersListParams {
	o.SetTokenAddress(tokenAddress)
	return o
}

// SetTokenAddress adds the tokenAddress to the safes transfers list params
func (o *SafesTransfersListParams) SetTokenAddress(tokenAddress *string) {
	o.TokenAddress = tokenAddress
}

// WithTransactionHash adds the transactionHash to the safes transfers list params
func (o *SafesTransfersListParams) WithTransactionHash(transactionHash *string) *SafesTransfersListParams {
	o.SetTransactionHash(transactionHash)
	return o
}

// SetTransactionHash adds the transactionHash to the safes transfers list params
func (o *SafesTransfersListParams) SetTransactionHash(transactionHash *string) {
	o.TransactionHash = transactionHash
}

// WithValue adds the value to the safes transfers list params
func (o *SafesTransfersListParams) WithValue(value *float64) *SafesTransfersListParams {
	o.SetValue(value)
	return o
}

// SetValue adds the value to the safes transfers list params
func (o *SafesTransfersListParams) SetValue(value *float64) {
	o.Value = value
}

// WithValueGt adds the valueGt to the safes transfers list params
func (o *SafesTransfersListParams) WithValueGt(valueGt *float64) *SafesTransfersListParams {
	o.SetValueGt(valueGt)
	return o
}

// SetValueGt adds the valueGt to the safes transfers list params
func (o *SafesTransfersListParams) SetValueGt(valueGt *float64) {
	o.ValueGt = valueGt
}

// WithValueLt adds the valueLt to the safes transfers list params
func (o *SafesTransfersListParams) WithValueLt(valueLt *float64) *SafesTransfersListParams {
	o.SetValueLt(valueLt)
	return o
}

// SetValueLt adds the valueLt to the safes transfers list params
func (o *SafesTransfersListParams) SetValueLt(valueLt *float64) {
	o.ValueLt = valueLt
}

// WriteToRequest writes these params to a swagger request
func (o *SafesTransfersListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.From != nil {

		// query param _from
		var qrFrom string

		if o.From != nil {
			qrFrom = *o.From
		}
		qFrom := qrFrom
		if qFrom != "" {

			if err := r.SetQueryParam("_from", qFrom); err != nil {
				return err
			}
		}
	}

	// path param address
	if err := r.SetPathParam("address", o.Address); err != nil {
		return err
	}

	if o.BlockNumber != nil {

		// query param block_number
		var qrBlockNumber float64

		if o.BlockNumber != nil {
			qrBlockNumber = *o.BlockNumber
		}
		qBlockNumber := swag.FormatFloat64(qrBlockNumber)
		if qBlockNumber != "" {

			if err := r.SetQueryParam("block_number", qBlockNumber); err != nil {
				return err
			}
		}
	}

	if o.BlockNumberGt != nil {

		// query param block_number__gt
		var qrBlockNumberGt float64

		if o.BlockNumberGt != nil {
			qrBlockNumberGt = *o.BlockNumberGt
		}
		qBlockNumberGt := swag.FormatFloat64(qrBlockNumberGt)
		if qBlockNumberGt != "" {

			if err := r.SetQueryParam("block_number__gt", qBlockNumberGt); err != nil {
				return err
			}
		}
	}

	if o.BlockNumberLt != nil {

		// query param block_number__lt
		var qrBlockNumberLt float64

		if o.BlockNumberLt != nil {
			qrBlockNumberLt = *o.BlockNumberLt
		}
		qBlockNumberLt := swag.FormatFloat64(qrBlockNumberLt)
		if qBlockNumberLt != "" {

			if err := r.SetQueryParam("block_number__lt", qBlockNumberLt); err != nil {
				return err
			}
		}
	}

	if o.Erc20 != nil {

		// query param erc20
		var qrErc20 string

		if o.Erc20 != nil {
			qrErc20 = *o.Erc20
		}
		qErc20 := qrErc20
		if qErc20 != "" {

			if err := r.SetQueryParam("erc20", qErc20); err != nil {
				return err
			}
		}
	}

	if o.Erc721 != nil {

		// query param erc721
		var qrErc721 string

		if o.Erc721 != nil {
			qrErc721 = *o.Erc721
		}
		qErc721 := qrErc721
		if qErc721 != "" {

			if err := r.SetQueryParam("erc721", qErc721); err != nil {
				return err
			}
		}
	}

	if o.Ether != nil {

		// query param ether
		var qrEther string

		if o.Ether != nil {
			qrEther = *o.Ether
		}
		qEther := qrEther
		if qEther != "" {

			if err := r.SetQueryParam("ether", qEther); err != nil {
				return err
			}
		}
	}

	if o.ExecutionDateGt != nil {

		// query param execution_date__gt
		var qrExecutionDateGt string

		if o.ExecutionDateGt != nil {
			qrExecutionDateGt = *o.ExecutionDateGt
		}
		qExecutionDateGt := qrExecutionDateGt
		if qExecutionDateGt != "" {

			if err := r.SetQueryParam("execution_date__gt", qExecutionDateGt); err != nil {
				return err
			}
		}
	}

	if o.ExecutionDateGte != nil {

		// query param execution_date__gte
		var qrExecutionDateGte string

		if o.ExecutionDateGte != nil {
			qrExecutionDateGte = *o.ExecutionDateGte
		}
		qExecutionDateGte := qrExecutionDateGte
		if qExecutionDateGte != "" {

			if err := r.SetQueryParam("execution_date__gte", qExecutionDateGte); err != nil {
				return err
			}
		}
	}

	if o.ExecutionDateLt != nil {

		// query param execution_date__lt
		var qrExecutionDateLt string

		if o.ExecutionDateLt != nil {
			qrExecutionDateLt = *o.ExecutionDateLt
		}
		qExecutionDateLt := qrExecutionDateLt
		if qExecutionDateLt != "" {

			if err := r.SetQueryParam("execution_date__lt", qExecutionDateLt); err != nil {
				return err
			}
		}
	}

	if o.ExecutionDateLte != nil {

		// query param execution_date__lte
		var qrExecutionDateLte string

		if o.ExecutionDateLte != nil {
			qrExecutionDateLte = *o.ExecutionDateLte
		}
		qExecutionDateLte := qrExecutionDateLte
		if qExecutionDateLte != "" {

			if err := r.SetQueryParam("execution_date__lte", qExecutionDateLte); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.To != nil {

		// query param to
		var qrTo string

		if o.To != nil {
			qrTo = *o.To
		}
		qTo := qrTo
		if qTo != "" {

			if err := r.SetQueryParam("to", qTo); err != nil {
				return err
			}
		}
	}

	if o.TokenAddress != nil {

		// query param token_address
		var qrTokenAddress string

		if o.TokenAddress != nil {
			qrTokenAddress = *o.TokenAddress
		}
		qTokenAddress := qrTokenAddress
		if qTokenAddress != "" {

			if err := r.SetQueryParam("token_address", qTokenAddress); err != nil {
				return err
			}
		}
	}

	if o.TransactionHash != nil {

		// query param transaction_hash
		var qrTransactionHash string

		if o.TransactionHash != nil {
			qrTransactionHash = *o.TransactionHash
		}
		qTransactionHash := qrTransactionHash
		if qTransactionHash != "" {

			if err := r.SetQueryParam("transaction_hash", qTransactionHash); err != nil {
				return err
			}
		}
	}

	if o.Value != nil {

		// query param value
		var qrValue float64

		if o.Value != nil {
			qrValue = *o.Value
		}
		qValue := swag.FormatFloat64(qrValue)
		if qValue != "" {

			if err := r.SetQueryParam("value", qValue); err != nil {
				return err
			}
		}
	}

	if o.ValueGt != nil {

		// query param value__gt
		var qrValueGt float64

		if o.ValueGt != nil {
			qrValueGt = *o.ValueGt
		}
		qValueGt := swag.FormatFloat64(qrValueGt)
		if qValueGt != "" {

			if err := r.SetQueryParam("value__gt", qValueGt); err != nil {
				return err
			}
		}
	}

	if o.ValueLt != nil {

		// query param value__lt
		var qrValueLt float64

		if o.ValueLt != nil {
			qrValueLt = *o.ValueLt
		}
		qValueLt := swag.FormatFloat64(qrValueLt)
		if qValueLt != "" {

			if err := r.SetQueryParam("value__lt", qValueLt); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
