// Code generated by go-swagger; DO NOT EDIT.

package safes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewSafesBalancesUsdListParams creates a new SafesBalancesUsdListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSafesBalancesUsdListParams() *SafesBalancesUsdListParams {
	return &SafesBalancesUsdListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSafesBalancesUsdListParamsWithTimeout creates a new SafesBalancesUsdListParams object
// with the ability to set a timeout on a request.
func NewSafesBalancesUsdListParamsWithTimeout(timeout time.Duration) *SafesBalancesUsdListParams {
	return &SafesBalancesUsdListParams{
		timeout: timeout,
	}
}

// NewSafesBalancesUsdListParamsWithContext creates a new SafesBalancesUsdListParams object
// with the ability to set a context for a request.
func NewSafesBalancesUsdListParamsWithContext(ctx context.Context) *SafesBalancesUsdListParams {
	return &SafesBalancesUsdListParams{
		Context: ctx,
	}
}

// NewSafesBalancesUsdListParamsWithHTTPClient creates a new SafesBalancesUsdListParams object
// with the ability to set a custom HTTPClient for a request.
func NewSafesBalancesUsdListParamsWithHTTPClient(client *http.Client) *SafesBalancesUsdListParams {
	return &SafesBalancesUsdListParams{
		HTTPClient: client,
	}
}

/* SafesBalancesUsdListParams contains all the parameters to send to the API endpoint
   for the safes balances usd list operation.

   Typically these are written to a http.Request.
*/
type SafesBalancesUsdListParams struct {

	// Address.
	Address string

	/* ExcludeSpam.

	   If `True` spam tokens will not be returned
	*/
	ExcludeSpam *bool

	/* Limit.

	   Number of results to return per page.
	*/
	Limit *int64

	/* Offset.

	   The initial index from which to return the results.
	*/
	Offset *int64

	/* Trusted.

	   If `True` just trusted tokens will be returned
	*/
	Trusted *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the safes balances usd list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SafesBalancesUsdListParams) WithDefaults() *SafesBalancesUsdListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the safes balances usd list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SafesBalancesUsdListParams) SetDefaults() {
	var (
		excludeSpamDefault = bool(false)

		trustedDefault = bool(false)
	)

	val := SafesBalancesUsdListParams{
		ExcludeSpam: &excludeSpamDefault,
		Trusted:     &trustedDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the safes balances usd list params
func (o *SafesBalancesUsdListParams) WithTimeout(timeout time.Duration) *SafesBalancesUsdListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the safes balances usd list params
func (o *SafesBalancesUsdListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the safes balances usd list params
func (o *SafesBalancesUsdListParams) WithContext(ctx context.Context) *SafesBalancesUsdListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the safes balances usd list params
func (o *SafesBalancesUsdListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the safes balances usd list params
func (o *SafesBalancesUsdListParams) WithHTTPClient(client *http.Client) *SafesBalancesUsdListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the safes balances usd list params
func (o *SafesBalancesUsdListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the safes balances usd list params
func (o *SafesBalancesUsdListParams) WithAddress(address string) *SafesBalancesUsdListParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the safes balances usd list params
func (o *SafesBalancesUsdListParams) SetAddress(address string) {
	o.Address = address
}

// WithExcludeSpam adds the excludeSpam to the safes balances usd list params
func (o *SafesBalancesUsdListParams) WithExcludeSpam(excludeSpam *bool) *SafesBalancesUsdListParams {
	o.SetExcludeSpam(excludeSpam)
	return o
}

// SetExcludeSpam adds the excludeSpam to the safes balances usd list params
func (o *SafesBalancesUsdListParams) SetExcludeSpam(excludeSpam *bool) {
	o.ExcludeSpam = excludeSpam
}

// WithLimit adds the limit to the safes balances usd list params
func (o *SafesBalancesUsdListParams) WithLimit(limit *int64) *SafesBalancesUsdListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the safes balances usd list params
func (o *SafesBalancesUsdListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the safes balances usd list params
func (o *SafesBalancesUsdListParams) WithOffset(offset *int64) *SafesBalancesUsdListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the safes balances usd list params
func (o *SafesBalancesUsdListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithTrusted adds the trusted to the safes balances usd list params
func (o *SafesBalancesUsdListParams) WithTrusted(trusted *bool) *SafesBalancesUsdListParams {
	o.SetTrusted(trusted)
	return o
}

// SetTrusted adds the trusted to the safes balances usd list params
func (o *SafesBalancesUsdListParams) SetTrusted(trusted *bool) {
	o.Trusted = trusted
}

// WriteToRequest writes these params to a swagger request
func (o *SafesBalancesUsdListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param address
	if err := r.SetPathParam("address", o.Address); err != nil {
		return err
	}

	if o.ExcludeSpam != nil {

		// query param exclude_spam
		var qrExcludeSpam bool

		if o.ExcludeSpam != nil {
			qrExcludeSpam = *o.ExcludeSpam
		}
		qExcludeSpam := swag.FormatBool(qrExcludeSpam)
		if qExcludeSpam != "" {

			if err := r.SetQueryParam("exclude_spam", qExcludeSpam); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Trusted != nil {

		// query param trusted
		var qrTrusted bool

		if o.Trusted != nil {
			qrTrusted = *o.Trusted
		}
		qTrusted := swag.FormatBool(qrTrusted)
		if qTrusted != "" {

			if err := r.SetQueryParam("trusted", qTrusted); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
