// Code generated by go-swagger; DO NOT EDIT.

package safes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSafesReadParams creates a new SafesReadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSafesReadParams() *SafesReadParams {
	return &SafesReadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSafesReadParamsWithTimeout creates a new SafesReadParams object
// with the ability to set a timeout on a request.
func NewSafesReadParamsWithTimeout(timeout time.Duration) *SafesReadParams {
	return &SafesReadParams{
		timeout: timeout,
	}
}

// NewSafesReadParamsWithContext creates a new SafesReadParams object
// with the ability to set a context for a request.
func NewSafesReadParamsWithContext(ctx context.Context) *SafesReadParams {
	return &SafesReadParams{
		Context: ctx,
	}
}

// NewSafesReadParamsWithHTTPClient creates a new SafesReadParams object
// with the ability to set a custom HTTPClient for a request.
func NewSafesReadParamsWithHTTPClient(client *http.Client) *SafesReadParams {
	return &SafesReadParams{
		HTTPClient: client,
	}
}

/* SafesReadParams contains all the parameters to send to the API endpoint
   for the safes read operation.

   Typically these are written to a http.Request.
*/
type SafesReadParams struct {

	// Address.
	Address string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the safes read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SafesReadParams) WithDefaults() *SafesReadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the safes read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SafesReadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the safes read params
func (o *SafesReadParams) WithTimeout(timeout time.Duration) *SafesReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the safes read params
func (o *SafesReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the safes read params
func (o *SafesReadParams) WithContext(ctx context.Context) *SafesReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the safes read params
func (o *SafesReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the safes read params
func (o *SafesReadParams) WithHTTPClient(client *http.Client) *SafesReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the safes read params
func (o *SafesReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the safes read params
func (o *SafesReadParams) WithAddress(address string) *SafesReadParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the safes read params
func (o *SafesReadParams) SetAddress(address string) {
	o.Address = address
}

// WriteToRequest writes these params to a swagger request
func (o *SafesReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param address
	if err := r.SetPathParam("address", o.Address); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
