// Code generated by go-swagger; DO NOT EDIT.

package safes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/MoonSHRD/dao-tg/pkg/gnosis/models"
)

// NewSafesDelegatesDeleteParams creates a new SafesDelegatesDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSafesDelegatesDeleteParams() *SafesDelegatesDeleteParams {
	return &SafesDelegatesDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSafesDelegatesDeleteParamsWithTimeout creates a new SafesDelegatesDeleteParams object
// with the ability to set a timeout on a request.
func NewSafesDelegatesDeleteParamsWithTimeout(timeout time.Duration) *SafesDelegatesDeleteParams {
	return &SafesDelegatesDeleteParams{
		timeout: timeout,
	}
}

// NewSafesDelegatesDeleteParamsWithContext creates a new SafesDelegatesDeleteParams object
// with the ability to set a context for a request.
func NewSafesDelegatesDeleteParamsWithContext(ctx context.Context) *SafesDelegatesDeleteParams {
	return &SafesDelegatesDeleteParams{
		Context: ctx,
	}
}

// NewSafesDelegatesDeleteParamsWithHTTPClient creates a new SafesDelegatesDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewSafesDelegatesDeleteParamsWithHTTPClient(client *http.Client) *SafesDelegatesDeleteParams {
	return &SafesDelegatesDeleteParams{
		HTTPClient: client,
	}
}

/* SafesDelegatesDeleteParams contains all the parameters to send to the API endpoint
   for the safes delegates delete operation.

   Typically these are written to a http.Request.
*/
type SafesDelegatesDeleteParams struct {

	// Address.
	Address string

	// Data.
	Data *models.SafeDelegateDelete

	// DelegateAddress.
	DelegateAddress string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the safes delegates delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SafesDelegatesDeleteParams) WithDefaults() *SafesDelegatesDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the safes delegates delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SafesDelegatesDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the safes delegates delete params
func (o *SafesDelegatesDeleteParams) WithTimeout(timeout time.Duration) *SafesDelegatesDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the safes delegates delete params
func (o *SafesDelegatesDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the safes delegates delete params
func (o *SafesDelegatesDeleteParams) WithContext(ctx context.Context) *SafesDelegatesDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the safes delegates delete params
func (o *SafesDelegatesDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the safes delegates delete params
func (o *SafesDelegatesDeleteParams) WithHTTPClient(client *http.Client) *SafesDelegatesDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the safes delegates delete params
func (o *SafesDelegatesDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the safes delegates delete params
func (o *SafesDelegatesDeleteParams) WithAddress(address string) *SafesDelegatesDeleteParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the safes delegates delete params
func (o *SafesDelegatesDeleteParams) SetAddress(address string) {
	o.Address = address
}

// WithData adds the data to the safes delegates delete params
func (o *SafesDelegatesDeleteParams) WithData(data *models.SafeDelegateDelete) *SafesDelegatesDeleteParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the safes delegates delete params
func (o *SafesDelegatesDeleteParams) SetData(data *models.SafeDelegateDelete) {
	o.Data = data
}

// WithDelegateAddress adds the delegateAddress to the safes delegates delete params
func (o *SafesDelegatesDeleteParams) WithDelegateAddress(delegateAddress string) *SafesDelegatesDeleteParams {
	o.SetDelegateAddress(delegateAddress)
	return o
}

// SetDelegateAddress adds the delegateAddress to the safes delegates delete params
func (o *SafesDelegatesDeleteParams) SetDelegateAddress(delegateAddress string) {
	o.DelegateAddress = delegateAddress
}

// WriteToRequest writes these params to a swagger request
func (o *SafesDelegatesDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param address
	if err := r.SetPathParam("address", o.Address); err != nil {
		return err
	}
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param delegate_address
	if err := r.SetPathParam("delegate_address", o.DelegateAddress); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
