// Code generated by go-swagger; DO NOT EDIT.

package safes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/MoonSHRD/dao-tg/pkg/gnosis/models"
)

// NewSafesDelegatesCreateParams creates a new SafesDelegatesCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSafesDelegatesCreateParams() *SafesDelegatesCreateParams {
	return &SafesDelegatesCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSafesDelegatesCreateParamsWithTimeout creates a new SafesDelegatesCreateParams object
// with the ability to set a timeout on a request.
func NewSafesDelegatesCreateParamsWithTimeout(timeout time.Duration) *SafesDelegatesCreateParams {
	return &SafesDelegatesCreateParams{
		timeout: timeout,
	}
}

// NewSafesDelegatesCreateParamsWithContext creates a new SafesDelegatesCreateParams object
// with the ability to set a context for a request.
func NewSafesDelegatesCreateParamsWithContext(ctx context.Context) *SafesDelegatesCreateParams {
	return &SafesDelegatesCreateParams{
		Context: ctx,
	}
}

// NewSafesDelegatesCreateParamsWithHTTPClient creates a new SafesDelegatesCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewSafesDelegatesCreateParamsWithHTTPClient(client *http.Client) *SafesDelegatesCreateParams {
	return &SafesDelegatesCreateParams{
		HTTPClient: client,
	}
}

/* SafesDelegatesCreateParams contains all the parameters to send to the API endpoint
   for the safes delegates create operation.

   Typically these are written to a http.Request.
*/
type SafesDelegatesCreateParams struct {

	// Address.
	Address string

	// Data.
	Data *models.SafeDelegate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the safes delegates create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SafesDelegatesCreateParams) WithDefaults() *SafesDelegatesCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the safes delegates create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SafesDelegatesCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the safes delegates create params
func (o *SafesDelegatesCreateParams) WithTimeout(timeout time.Duration) *SafesDelegatesCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the safes delegates create params
func (o *SafesDelegatesCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the safes delegates create params
func (o *SafesDelegatesCreateParams) WithContext(ctx context.Context) *SafesDelegatesCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the safes delegates create params
func (o *SafesDelegatesCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the safes delegates create params
func (o *SafesDelegatesCreateParams) WithHTTPClient(client *http.Client) *SafesDelegatesCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the safes delegates create params
func (o *SafesDelegatesCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the safes delegates create params
func (o *SafesDelegatesCreateParams) WithAddress(address string) *SafesDelegatesCreateParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the safes delegates create params
func (o *SafesDelegatesCreateParams) SetAddress(address string) {
	o.Address = address
}

// WithData adds the data to the safes delegates create params
func (o *SafesDelegatesCreateParams) WithData(data *models.SafeDelegate) *SafesDelegatesCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the safes delegates create params
func (o *SafesDelegatesCreateParams) SetData(data *models.SafeDelegate) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *SafesDelegatesCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param address
	if err := r.SetPathParam("address", o.Address); err != nil {
		return err
	}
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
