// Code generated by go-swagger; DO NOT EDIT.

package safes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSafesDelegatesDeleteAllParams creates a new SafesDelegatesDeleteAllParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSafesDelegatesDeleteAllParams() *SafesDelegatesDeleteAllParams {
	return &SafesDelegatesDeleteAllParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSafesDelegatesDeleteAllParamsWithTimeout creates a new SafesDelegatesDeleteAllParams object
// with the ability to set a timeout on a request.
func NewSafesDelegatesDeleteAllParamsWithTimeout(timeout time.Duration) *SafesDelegatesDeleteAllParams {
	return &SafesDelegatesDeleteAllParams{
		timeout: timeout,
	}
}

// NewSafesDelegatesDeleteAllParamsWithContext creates a new SafesDelegatesDeleteAllParams object
// with the ability to set a context for a request.
func NewSafesDelegatesDeleteAllParamsWithContext(ctx context.Context) *SafesDelegatesDeleteAllParams {
	return &SafesDelegatesDeleteAllParams{
		Context: ctx,
	}
}

// NewSafesDelegatesDeleteAllParamsWithHTTPClient creates a new SafesDelegatesDeleteAllParams object
// with the ability to set a custom HTTPClient for a request.
func NewSafesDelegatesDeleteAllParamsWithHTTPClient(client *http.Client) *SafesDelegatesDeleteAllParams {
	return &SafesDelegatesDeleteAllParams{
		HTTPClient: client,
	}
}

/* SafesDelegatesDeleteAllParams contains all the parameters to send to the API endpoint
   for the safes delegates delete all operation.

   Typically these are written to a http.Request.
*/
type SafesDelegatesDeleteAllParams struct {

	// Address.
	Address string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the safes delegates delete all params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SafesDelegatesDeleteAllParams) WithDefaults() *SafesDelegatesDeleteAllParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the safes delegates delete all params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SafesDelegatesDeleteAllParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the safes delegates delete all params
func (o *SafesDelegatesDeleteAllParams) WithTimeout(timeout time.Duration) *SafesDelegatesDeleteAllParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the safes delegates delete all params
func (o *SafesDelegatesDeleteAllParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the safes delegates delete all params
func (o *SafesDelegatesDeleteAllParams) WithContext(ctx context.Context) *SafesDelegatesDeleteAllParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the safes delegates delete all params
func (o *SafesDelegatesDeleteAllParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the safes delegates delete all params
func (o *SafesDelegatesDeleteAllParams) WithHTTPClient(client *http.Client) *SafesDelegatesDeleteAllParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the safes delegates delete all params
func (o *SafesDelegatesDeleteAllParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the safes delegates delete all params
func (o *SafesDelegatesDeleteAllParams) WithAddress(address string) *SafesDelegatesDeleteAllParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the safes delegates delete all params
func (o *SafesDelegatesDeleteAllParams) SetAddress(address string) {
	o.Address = address
}

// WriteToRequest writes these params to a swagger request
func (o *SafesDelegatesDeleteAllParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param address
	if err := r.SetPathParam("address", o.Address); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
