// Code generated by go-swagger; DO NOT EDIT.

package safes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewSafesTransactionsListParams creates a new SafesTransactionsListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSafesTransactionsListParams() *SafesTransactionsListParams {
	return &SafesTransactionsListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSafesTransactionsListParamsWithTimeout creates a new SafesTransactionsListParams object
// with the ability to set a timeout on a request.
func NewSafesTransactionsListParamsWithTimeout(timeout time.Duration) *SafesTransactionsListParams {
	return &SafesTransactionsListParams{
		timeout: timeout,
	}
}

// NewSafesTransactionsListParamsWithContext creates a new SafesTransactionsListParams object
// with the ability to set a context for a request.
func NewSafesTransactionsListParamsWithContext(ctx context.Context) *SafesTransactionsListParams {
	return &SafesTransactionsListParams{
		Context: ctx,
	}
}

// NewSafesTransactionsListParamsWithHTTPClient creates a new SafesTransactionsListParams object
// with the ability to set a custom HTTPClient for a request.
func NewSafesTransactionsListParamsWithHTTPClient(client *http.Client) *SafesTransactionsListParams {
	return &SafesTransactionsListParams{
		HTTPClient: client,
	}
}

/* SafesTransactionsListParams contains all the parameters to send to the API endpoint
   for the safes transactions list operation.

   Typically these are written to a http.Request.
*/
type SafesTransactionsListParams struct {

	// Address.
	Address string

	// Executed.
	Executed *string

	// ExecutionDateGte.
	ExecutionDateGte *string

	// ExecutionDateLte.
	ExecutionDateLte *string

	// Failed.
	Failed *string

	// HasConfirmations.
	HasConfirmations *string

	/* Limit.

	   Number of results to return per page.
	*/
	Limit *int64

	// ModifiedGt.
	ModifiedGt *string

	// ModifiedGte.
	ModifiedGte *string

	// ModifiedLt.
	ModifiedLt *string

	// ModifiedLte.
	ModifiedLte *string

	// Nonce.
	Nonce *float64

	// NonceGt.
	NonceGt *float64

	// NonceGte.
	NonceGte *float64

	// NonceLt.
	NonceLt *float64

	// NonceLte.
	NonceLte *float64

	/* Offset.

	   The initial index from which to return the results.
	*/
	Offset *int64

	/* Ordering.

	   Which field to use when ordering the results.
	*/
	Ordering *string

	// SafeTxHash.
	SafeTxHash *string

	// SubmissionDateGte.
	SubmissionDateGte *string

	// SubmissionDateLte.
	SubmissionDateLte *string

	// To.
	To *string

	// TransactionHash.
	TransactionHash *string

	// Trusted.
	Trusted *string

	// Value.
	Value *float64

	// ValueGt.
	ValueGt *float64

	// ValueLt.
	ValueLt *float64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the safes transactions list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SafesTransactionsListParams) WithDefaults() *SafesTransactionsListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the safes transactions list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SafesTransactionsListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the safes transactions list params
func (o *SafesTransactionsListParams) WithTimeout(timeout time.Duration) *SafesTransactionsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the safes transactions list params
func (o *SafesTransactionsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the safes transactions list params
func (o *SafesTransactionsListParams) WithContext(ctx context.Context) *SafesTransactionsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the safes transactions list params
func (o *SafesTransactionsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the safes transactions list params
func (o *SafesTransactionsListParams) WithHTTPClient(client *http.Client) *SafesTransactionsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the safes transactions list params
func (o *SafesTransactionsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the safes transactions list params
func (o *SafesTransactionsListParams) WithAddress(address string) *SafesTransactionsListParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the safes transactions list params
func (o *SafesTransactionsListParams) SetAddress(address string) {
	o.Address = address
}

// WithExecuted adds the executed to the safes transactions list params
func (o *SafesTransactionsListParams) WithExecuted(executed *string) *SafesTransactionsListParams {
	o.SetExecuted(executed)
	return o
}

// SetExecuted adds the executed to the safes transactions list params
func (o *SafesTransactionsListParams) SetExecuted(executed *string) {
	o.Executed = executed
}

// WithExecutionDateGte adds the executionDateGte to the safes transactions list params
func (o *SafesTransactionsListParams) WithExecutionDateGte(executionDateGte *string) *SafesTransactionsListParams {
	o.SetExecutionDateGte(executionDateGte)
	return o
}

// SetExecutionDateGte adds the executionDateGte to the safes transactions list params
func (o *SafesTransactionsListParams) SetExecutionDateGte(executionDateGte *string) {
	o.ExecutionDateGte = executionDateGte
}

// WithExecutionDateLte adds the executionDateLte to the safes transactions list params
func (o *SafesTransactionsListParams) WithExecutionDateLte(executionDateLte *string) *SafesTransactionsListParams {
	o.SetExecutionDateLte(executionDateLte)
	return o
}

// SetExecutionDateLte adds the executionDateLte to the safes transactions list params
func (o *SafesTransactionsListParams) SetExecutionDateLte(executionDateLte *string) {
	o.ExecutionDateLte = executionDateLte
}

// WithFailed adds the failed to the safes transactions list params
func (o *SafesTransactionsListParams) WithFailed(failed *string) *SafesTransactionsListParams {
	o.SetFailed(failed)
	return o
}

// SetFailed adds the failed to the safes transactions list params
func (o *SafesTransactionsListParams) SetFailed(failed *string) {
	o.Failed = failed
}

// WithHasConfirmations adds the hasConfirmations to the safes transactions list params
func (o *SafesTransactionsListParams) WithHasConfirmations(hasConfirmations *string) *SafesTransactionsListParams {
	o.SetHasConfirmations(hasConfirmations)
	return o
}

// SetHasConfirmations adds the hasConfirmations to the safes transactions list params
func (o *SafesTransactionsListParams) SetHasConfirmations(hasConfirmations *string) {
	o.HasConfirmations = hasConfirmations
}

// WithLimit adds the limit to the safes transactions list params
func (o *SafesTransactionsListParams) WithLimit(limit *int64) *SafesTransactionsListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the safes transactions list params
func (o *SafesTransactionsListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithModifiedGt adds the modifiedGt to the safes transactions list params
func (o *SafesTransactionsListParams) WithModifiedGt(modifiedGt *string) *SafesTransactionsListParams {
	o.SetModifiedGt(modifiedGt)
	return o
}

// SetModifiedGt adds the modifiedGt to the safes transactions list params
func (o *SafesTransactionsListParams) SetModifiedGt(modifiedGt *string) {
	o.ModifiedGt = modifiedGt
}

// WithModifiedGte adds the modifiedGte to the safes transactions list params
func (o *SafesTransactionsListParams) WithModifiedGte(modifiedGte *string) *SafesTransactionsListParams {
	o.SetModifiedGte(modifiedGte)
	return o
}

// SetModifiedGte adds the modifiedGte to the safes transactions list params
func (o *SafesTransactionsListParams) SetModifiedGte(modifiedGte *string) {
	o.ModifiedGte = modifiedGte
}

// WithModifiedLt adds the modifiedLt to the safes transactions list params
func (o *SafesTransactionsListParams) WithModifiedLt(modifiedLt *string) *SafesTransactionsListParams {
	o.SetModifiedLt(modifiedLt)
	return o
}

// SetModifiedLt adds the modifiedLt to the safes transactions list params
func (o *SafesTransactionsListParams) SetModifiedLt(modifiedLt *string) {
	o.ModifiedLt = modifiedLt
}

// WithModifiedLte adds the modifiedLte to the safes transactions list params
func (o *SafesTransactionsListParams) WithModifiedLte(modifiedLte *string) *SafesTransactionsListParams {
	o.SetModifiedLte(modifiedLte)
	return o
}

// SetModifiedLte adds the modifiedLte to the safes transactions list params
func (o *SafesTransactionsListParams) SetModifiedLte(modifiedLte *string) {
	o.ModifiedLte = modifiedLte
}

// WithNonce adds the nonce to the safes transactions list params
func (o *SafesTransactionsListParams) WithNonce(nonce *float64) *SafesTransactionsListParams {
	o.SetNonce(nonce)
	return o
}

// SetNonce adds the nonce to the safes transactions list params
func (o *SafesTransactionsListParams) SetNonce(nonce *float64) {
	o.Nonce = nonce
}

// WithNonceGt adds the nonceGt to the safes transactions list params
func (o *SafesTransactionsListParams) WithNonceGt(nonceGt *float64) *SafesTransactionsListParams {
	o.SetNonceGt(nonceGt)
	return o
}

// SetNonceGt adds the nonceGt to the safes transactions list params
func (o *SafesTransactionsListParams) SetNonceGt(nonceGt *float64) {
	o.NonceGt = nonceGt
}

// WithNonceGte adds the nonceGte to the safes transactions list params
func (o *SafesTransactionsListParams) WithNonceGte(nonceGte *float64) *SafesTransactionsListParams {
	o.SetNonceGte(nonceGte)
	return o
}

// SetNonceGte adds the nonceGte to the safes transactions list params
func (o *SafesTransactionsListParams) SetNonceGte(nonceGte *float64) {
	o.NonceGte = nonceGte
}

// WithNonceLt adds the nonceLt to the safes transactions list params
func (o *SafesTransactionsListParams) WithNonceLt(nonceLt *float64) *SafesTransactionsListParams {
	o.SetNonceLt(nonceLt)
	return o
}

// SetNonceLt adds the nonceLt to the safes transactions list params
func (o *SafesTransactionsListParams) SetNonceLt(nonceLt *float64) {
	o.NonceLt = nonceLt
}

// WithNonceLte adds the nonceLte to the safes transactions list params
func (o *SafesTransactionsListParams) WithNonceLte(nonceLte *float64) *SafesTransactionsListParams {
	o.SetNonceLte(nonceLte)
	return o
}

// SetNonceLte adds the nonceLte to the safes transactions list params
func (o *SafesTransactionsListParams) SetNonceLte(nonceLte *float64) {
	o.NonceLte = nonceLte
}

// WithOffset adds the offset to the safes transactions list params
func (o *SafesTransactionsListParams) WithOffset(offset *int64) *SafesTransactionsListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the safes transactions list params
func (o *SafesTransactionsListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithOrdering adds the ordering to the safes transactions list params
func (o *SafesTransactionsListParams) WithOrdering(ordering *string) *SafesTransactionsListParams {
	o.SetOrdering(ordering)
	return o
}

// SetOrdering adds the ordering to the safes transactions list params
func (o *SafesTransactionsListParams) SetOrdering(ordering *string) {
	o.Ordering = ordering
}

// WithSafeTxHash adds the safeTxHash to the safes transactions list params
func (o *SafesTransactionsListParams) WithSafeTxHash(safeTxHash *string) *SafesTransactionsListParams {
	o.SetSafeTxHash(safeTxHash)
	return o
}

// SetSafeTxHash adds the safeTxHash to the safes transactions list params
func (o *SafesTransactionsListParams) SetSafeTxHash(safeTxHash *string) {
	o.SafeTxHash = safeTxHash
}

// WithSubmissionDateGte adds the submissionDateGte to the safes transactions list params
func (o *SafesTransactionsListParams) WithSubmissionDateGte(submissionDateGte *string) *SafesTransactionsListParams {
	o.SetSubmissionDateGte(submissionDateGte)
	return o
}

// SetSubmissionDateGte adds the submissionDateGte to the safes transactions list params
func (o *SafesTransactionsListParams) SetSubmissionDateGte(submissionDateGte *string) {
	o.SubmissionDateGte = submissionDateGte
}

// WithSubmissionDateLte adds the submissionDateLte to the safes transactions list params
func (o *SafesTransactionsListParams) WithSubmissionDateLte(submissionDateLte *string) *SafesTransactionsListParams {
	o.SetSubmissionDateLte(submissionDateLte)
	return o
}

// SetSubmissionDateLte adds the submissionDateLte to the safes transactions list params
func (o *SafesTransactionsListParams) SetSubmissionDateLte(submissionDateLte *string) {
	o.SubmissionDateLte = submissionDateLte
}

// WithTo adds the to to the safes transactions list params
func (o *SafesTransactionsListParams) WithTo(to *string) *SafesTransactionsListParams {
	o.SetTo(to)
	return o
}

// SetTo adds the to to the safes transactions list params
func (o *SafesTransactionsListParams) SetTo(to *string) {
	o.To = to
}

// WithTransactionHash adds the transactionHash to the safes transactions list params
func (o *SafesTransactionsListParams) WithTransactionHash(transactionHash *string) *SafesTransactionsListParams {
	o.SetTransactionHash(transactionHash)
	return o
}

// SetTransactionHash adds the transactionHash to the safes transactions list params
func (o *SafesTransactionsListParams) SetTransactionHash(transactionHash *string) {
	o.TransactionHash = transactionHash
}

// WithTrusted adds the trusted to the safes transactions list params
func (o *SafesTransactionsListParams) WithTrusted(trusted *string) *SafesTransactionsListParams {
	o.SetTrusted(trusted)
	return o
}

// SetTrusted adds the trusted to the safes transactions list params
func (o *SafesTransactionsListParams) SetTrusted(trusted *string) {
	o.Trusted = trusted
}

// WithValue adds the value to the safes transactions list params
func (o *SafesTransactionsListParams) WithValue(value *float64) *SafesTransactionsListParams {
	o.SetValue(value)
	return o
}

// SetValue adds the value to the safes transactions list params
func (o *SafesTransactionsListParams) SetValue(value *float64) {
	o.Value = value
}

// WithValueGt adds the valueGt to the safes transactions list params
func (o *SafesTransactionsListParams) WithValueGt(valueGt *float64) *SafesTransactionsListParams {
	o.SetValueGt(valueGt)
	return o
}

// SetValueGt adds the valueGt to the safes transactions list params
func (o *SafesTransactionsListParams) SetValueGt(valueGt *float64) {
	o.ValueGt = valueGt
}

// WithValueLt adds the valueLt to the safes transactions list params
func (o *SafesTransactionsListParams) WithValueLt(valueLt *float64) *SafesTransactionsListParams {
	o.SetValueLt(valueLt)
	return o
}

// SetValueLt adds the valueLt to the safes transactions list params
func (o *SafesTransactionsListParams) SetValueLt(valueLt *float64) {
	o.ValueLt = valueLt
}

// WriteToRequest writes these params to a swagger request
func (o *SafesTransactionsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param address
	if err := r.SetPathParam("address", o.Address); err != nil {
		return err
	}

	if o.Executed != nil {

		// query param executed
		var qrExecuted string

		if o.Executed != nil {
			qrExecuted = *o.Executed
		}
		qExecuted := qrExecuted
		if qExecuted != "" {

			if err := r.SetQueryParam("executed", qExecuted); err != nil {
				return err
			}
		}
	}

	if o.ExecutionDateGte != nil {

		// query param execution_date__gte
		var qrExecutionDateGte string

		if o.ExecutionDateGte != nil {
			qrExecutionDateGte = *o.ExecutionDateGte
		}
		qExecutionDateGte := qrExecutionDateGte
		if qExecutionDateGte != "" {

			if err := r.SetQueryParam("execution_date__gte", qExecutionDateGte); err != nil {
				return err
			}
		}
	}

	if o.ExecutionDateLte != nil {

		// query param execution_date__lte
		var qrExecutionDateLte string

		if o.ExecutionDateLte != nil {
			qrExecutionDateLte = *o.ExecutionDateLte
		}
		qExecutionDateLte := qrExecutionDateLte
		if qExecutionDateLte != "" {

			if err := r.SetQueryParam("execution_date__lte", qExecutionDateLte); err != nil {
				return err
			}
		}
	}

	if o.Failed != nil {

		// query param failed
		var qrFailed string

		if o.Failed != nil {
			qrFailed = *o.Failed
		}
		qFailed := qrFailed
		if qFailed != "" {

			if err := r.SetQueryParam("failed", qFailed); err != nil {
				return err
			}
		}
	}

	if o.HasConfirmations != nil {

		// query param has_confirmations
		var qrHasConfirmations string

		if o.HasConfirmations != nil {
			qrHasConfirmations = *o.HasConfirmations
		}
		qHasConfirmations := qrHasConfirmations
		if qHasConfirmations != "" {

			if err := r.SetQueryParam("has_confirmations", qHasConfirmations); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.ModifiedGt != nil {

		// query param modified__gt
		var qrModifiedGt string

		if o.ModifiedGt != nil {
			qrModifiedGt = *o.ModifiedGt
		}
		qModifiedGt := qrModifiedGt
		if qModifiedGt != "" {

			if err := r.SetQueryParam("modified__gt", qModifiedGt); err != nil {
				return err
			}
		}
	}

	if o.ModifiedGte != nil {

		// query param modified__gte
		var qrModifiedGte string

		if o.ModifiedGte != nil {
			qrModifiedGte = *o.ModifiedGte
		}
		qModifiedGte := qrModifiedGte
		if qModifiedGte != "" {

			if err := r.SetQueryParam("modified__gte", qModifiedGte); err != nil {
				return err
			}
		}
	}

	if o.ModifiedLt != nil {

		// query param modified__lt
		var qrModifiedLt string

		if o.ModifiedLt != nil {
			qrModifiedLt = *o.ModifiedLt
		}
		qModifiedLt := qrModifiedLt
		if qModifiedLt != "" {

			if err := r.SetQueryParam("modified__lt", qModifiedLt); err != nil {
				return err
			}
		}
	}

	if o.ModifiedLte != nil {

		// query param modified__lte
		var qrModifiedLte string

		if o.ModifiedLte != nil {
			qrModifiedLte = *o.ModifiedLte
		}
		qModifiedLte := qrModifiedLte
		if qModifiedLte != "" {

			if err := r.SetQueryParam("modified__lte", qModifiedLte); err != nil {
				return err
			}
		}
	}

	if o.Nonce != nil {

		// query param nonce
		var qrNonce float64

		if o.Nonce != nil {
			qrNonce = *o.Nonce
		}
		qNonce := swag.FormatFloat64(qrNonce)
		if qNonce != "" {

			if err := r.SetQueryParam("nonce", qNonce); err != nil {
				return err
			}
		}
	}

	if o.NonceGt != nil {

		// query param nonce__gt
		var qrNonceGt float64

		if o.NonceGt != nil {
			qrNonceGt = *o.NonceGt
		}
		qNonceGt := swag.FormatFloat64(qrNonceGt)
		if qNonceGt != "" {

			if err := r.SetQueryParam("nonce__gt", qNonceGt); err != nil {
				return err
			}
		}
	}

	if o.NonceGte != nil {

		// query param nonce__gte
		var qrNonceGte float64

		if o.NonceGte != nil {
			qrNonceGte = *o.NonceGte
		}
		qNonceGte := swag.FormatFloat64(qrNonceGte)
		if qNonceGte != "" {

			if err := r.SetQueryParam("nonce__gte", qNonceGte); err != nil {
				return err
			}
		}
	}

	if o.NonceLt != nil {

		// query param nonce__lt
		var qrNonceLt float64

		if o.NonceLt != nil {
			qrNonceLt = *o.NonceLt
		}
		qNonceLt := swag.FormatFloat64(qrNonceLt)
		if qNonceLt != "" {

			if err := r.SetQueryParam("nonce__lt", qNonceLt); err != nil {
				return err
			}
		}
	}

	if o.NonceLte != nil {

		// query param nonce__lte
		var qrNonceLte float64

		if o.NonceLte != nil {
			qrNonceLte = *o.NonceLte
		}
		qNonceLte := swag.FormatFloat64(qrNonceLte)
		if qNonceLte != "" {

			if err := r.SetQueryParam("nonce__lte", qNonceLte); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Ordering != nil {

		// query param ordering
		var qrOrdering string

		if o.Ordering != nil {
			qrOrdering = *o.Ordering
		}
		qOrdering := qrOrdering
		if qOrdering != "" {

			if err := r.SetQueryParam("ordering", qOrdering); err != nil {
				return err
			}
		}
	}

	if o.SafeTxHash != nil {

		// query param safe_tx_hash
		var qrSafeTxHash string

		if o.SafeTxHash != nil {
			qrSafeTxHash = *o.SafeTxHash
		}
		qSafeTxHash := qrSafeTxHash
		if qSafeTxHash != "" {

			if err := r.SetQueryParam("safe_tx_hash", qSafeTxHash); err != nil {
				return err
			}
		}
	}

	if o.SubmissionDateGte != nil {

		// query param submission_date__gte
		var qrSubmissionDateGte string

		if o.SubmissionDateGte != nil {
			qrSubmissionDateGte = *o.SubmissionDateGte
		}
		qSubmissionDateGte := qrSubmissionDateGte
		if qSubmissionDateGte != "" {

			if err := r.SetQueryParam("submission_date__gte", qSubmissionDateGte); err != nil {
				return err
			}
		}
	}

	if o.SubmissionDateLte != nil {

		// query param submission_date__lte
		var qrSubmissionDateLte string

		if o.SubmissionDateLte != nil {
			qrSubmissionDateLte = *o.SubmissionDateLte
		}
		qSubmissionDateLte := qrSubmissionDateLte
		if qSubmissionDateLte != "" {

			if err := r.SetQueryParam("submission_date__lte", qSubmissionDateLte); err != nil {
				return err
			}
		}
	}

	if o.To != nil {

		// query param to
		var qrTo string

		if o.To != nil {
			qrTo = *o.To
		}
		qTo := qrTo
		if qTo != "" {

			if err := r.SetQueryParam("to", qTo); err != nil {
				return err
			}
		}
	}

	if o.TransactionHash != nil {

		// query param transaction_hash
		var qrTransactionHash string

		if o.TransactionHash != nil {
			qrTransactionHash = *o.TransactionHash
		}
		qTransactionHash := qrTransactionHash
		if qTransactionHash != "" {

			if err := r.SetQueryParam("transaction_hash", qTransactionHash); err != nil {
				return err
			}
		}
	}

	if o.Trusted != nil {

		// query param trusted
		var qrTrusted string

		if o.Trusted != nil {
			qrTrusted = *o.Trusted
		}
		qTrusted := qrTrusted
		if qTrusted != "" {

			if err := r.SetQueryParam("trusted", qTrusted); err != nil {
				return err
			}
		}
	}

	if o.Value != nil {

		// query param value
		var qrValue float64

		if o.Value != nil {
			qrValue = *o.Value
		}
		qValue := swag.FormatFloat64(qrValue)
		if qValue != "" {

			if err := r.SetQueryParam("value", qValue); err != nil {
				return err
			}
		}
	}

	if o.ValueGt != nil {

		// query param value__gt
		var qrValueGt float64

		if o.ValueGt != nil {
			qrValueGt = *o.ValueGt
		}
		qValueGt := swag.FormatFloat64(qrValueGt)
		if qValueGt != "" {

			if err := r.SetQueryParam("value__gt", qValueGt); err != nil {
				return err
			}
		}
	}

	if o.ValueLt != nil {

		// query param value__lt
		var qrValueLt float64

		if o.ValueLt != nil {
			qrValueLt = *o.ValueLt
		}
		qValueLt := swag.FormatFloat64(qrValueLt)
		if qValueLt != "" {

			if err := r.SetQueryParam("value__lt", qValueLt); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
