// Code generated by go-swagger; DO NOT EDIT.

package safes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MoonSHRD/dao-tg/pkg/gnosis/models"
)

// SafesCollectiblesListReader is a Reader for the SafesCollectiblesList structure.
type SafesCollectiblesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SafesCollectiblesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSafesCollectiblesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewSafesCollectiblesListNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewSafesCollectiblesListUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSafesCollectiblesListOK creates a SafesCollectiblesListOK with default headers values
func NewSafesCollectiblesListOK() *SafesCollectiblesListOK {
	return &SafesCollectiblesListOK{}
}

/* SafesCollectiblesListOK describes a response with status code 200, with default header values.

SafesCollectiblesListOK safes collectibles list o k
*/
type SafesCollectiblesListOK struct {
	Payload []*models.SafeCollectibleResponse
}

func (o *SafesCollectiblesListOK) Error() string {
	return fmt.Sprintf("[GET /safes/{address}/collectibles/][%d] safesCollectiblesListOK  %+v", 200, o.Payload)
}
func (o *SafesCollectiblesListOK) GetPayload() []*models.SafeCollectibleResponse {
	return o.Payload
}

func (o *SafesCollectiblesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSafesCollectiblesListNotFound creates a SafesCollectiblesListNotFound with default headers values
func NewSafesCollectiblesListNotFound() *SafesCollectiblesListNotFound {
	return &SafesCollectiblesListNotFound{}
}

/* SafesCollectiblesListNotFound describes a response with status code 404, with default header values.

Safe not found
*/
type SafesCollectiblesListNotFound struct {
}

func (o *SafesCollectiblesListNotFound) Error() string {
	return fmt.Sprintf("[GET /safes/{address}/collectibles/][%d] safesCollectiblesListNotFound ", 404)
}

func (o *SafesCollectiblesListNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSafesCollectiblesListUnprocessableEntity creates a SafesCollectiblesListUnprocessableEntity with default headers values
func NewSafesCollectiblesListUnprocessableEntity() *SafesCollectiblesListUnprocessableEntity {
	return &SafesCollectiblesListUnprocessableEntity{}
}

/* SafesCollectiblesListUnprocessableEntity describes a response with status code 422, with default header values.

Safe address checksum not valid
*/
type SafesCollectiblesListUnprocessableEntity struct {
}

func (o *SafesCollectiblesListUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /safes/{address}/collectibles/][%d] safesCollectiblesListUnprocessableEntity ", 422)
}

func (o *SafesCollectiblesListUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
