// Code generated by go-swagger; DO NOT EDIT.

package safes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/MoonSHRD/dao-tg/pkg/gnosis/models"
)

// SafesMultisigTransactionsListReader is a Reader for the SafesMultisigTransactionsList structure.
type SafesMultisigTransactionsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SafesMultisigTransactionsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSafesMultisigTransactionsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSafesMultisigTransactionsListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewSafesMultisigTransactionsListUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSafesMultisigTransactionsListOK creates a SafesMultisigTransactionsListOK with default headers values
func NewSafesMultisigTransactionsListOK() *SafesMultisigTransactionsListOK {
	return &SafesMultisigTransactionsListOK{}
}

/* SafesMultisigTransactionsListOK describes a response with status code 200, with default header values.

SafesMultisigTransactionsListOK safes multisig transactions list o k
*/
type SafesMultisigTransactionsListOK struct {
	Payload *SafesMultisigTransactionsListOKBody
}

func (o *SafesMultisigTransactionsListOK) Error() string {
	return fmt.Sprintf("[GET /safes/{address}/multisig-transactions/][%d] safesMultisigTransactionsListOK  %+v", 200, o.Payload)
}
func (o *SafesMultisigTransactionsListOK) GetPayload() *SafesMultisigTransactionsListOKBody {
	return o.Payload
}

func (o *SafesMultisigTransactionsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SafesMultisigTransactionsListOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSafesMultisigTransactionsListBadRequest creates a SafesMultisigTransactionsListBadRequest with default headers values
func NewSafesMultisigTransactionsListBadRequest() *SafesMultisigTransactionsListBadRequest {
	return &SafesMultisigTransactionsListBadRequest{}
}

/* SafesMultisigTransactionsListBadRequest describes a response with status code 400, with default header values.

Invalid data
*/
type SafesMultisigTransactionsListBadRequest struct {
}

func (o *SafesMultisigTransactionsListBadRequest) Error() string {
	return fmt.Sprintf("[GET /safes/{address}/multisig-transactions/][%d] safesMultisigTransactionsListBadRequest ", 400)
}

func (o *SafesMultisigTransactionsListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSafesMultisigTransactionsListUnprocessableEntity creates a SafesMultisigTransactionsListUnprocessableEntity with default headers values
func NewSafesMultisigTransactionsListUnprocessableEntity() *SafesMultisigTransactionsListUnprocessableEntity {
	return &SafesMultisigTransactionsListUnprocessableEntity{}
}

/* SafesMultisigTransactionsListUnprocessableEntity describes a response with status code 422, with default header values.

Invalid ethereum address
*/
type SafesMultisigTransactionsListUnprocessableEntity struct {
}

func (o *SafesMultisigTransactionsListUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /safes/{address}/multisig-transactions/][%d] safesMultisigTransactionsListUnprocessableEntity ", 422)
}

func (o *SafesMultisigTransactionsListUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*SafesMultisigTransactionsListOKBody safes multisig transactions list o k body
swagger:model SafesMultisigTransactionsListOKBody
*/
type SafesMultisigTransactionsListOKBody struct {

	// count
	// Required: true
	Count *int64 `json:"count"`

	// next
	// Format: uri
	Next *strfmt.URI `json:"next,omitempty"`

	// previous
	// Format: uri
	Previous *strfmt.URI `json:"previous,omitempty"`

	// results
	// Required: true
	Results []*models.SafeMultisigTransactionResponse `json:"results"`
}

// Validate validates this safes multisig transactions list o k body
func (o *SafesMultisigTransactionsListOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCount(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateNext(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePrevious(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateResults(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SafesMultisigTransactionsListOKBody) validateCount(formats strfmt.Registry) error {

	if err := validate.Required("safesMultisigTransactionsListOK"+"."+"count", "body", o.Count); err != nil {
		return err
	}

	return nil
}

func (o *SafesMultisigTransactionsListOKBody) validateNext(formats strfmt.Registry) error {
	if swag.IsZero(o.Next) { // not required
		return nil
	}

	if err := validate.FormatOf("safesMultisigTransactionsListOK"+"."+"next", "body", "uri", o.Next.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *SafesMultisigTransactionsListOKBody) validatePrevious(formats strfmt.Registry) error {
	if swag.IsZero(o.Previous) { // not required
		return nil
	}

	if err := validate.FormatOf("safesMultisigTransactionsListOK"+"."+"previous", "body", "uri", o.Previous.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *SafesMultisigTransactionsListOKBody) validateResults(formats strfmt.Registry) error {

	if err := validate.Required("safesMultisigTransactionsListOK"+"."+"results", "body", o.Results); err != nil {
		return err
	}

	for i := 0; i < len(o.Results); i++ {
		if swag.IsZero(o.Results[i]) { // not required
			continue
		}

		if o.Results[i] != nil {
			if err := o.Results[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("safesMultisigTransactionsListOK" + "." + "results" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("safesMultisigTransactionsListOK" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this safes multisig transactions list o k body based on the context it is used
func (o *SafesMultisigTransactionsListOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResults(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SafesMultisigTransactionsListOKBody) contextValidateResults(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Results); i++ {

		if o.Results[i] != nil {
			if err := o.Results[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("safesMultisigTransactionsListOK" + "." + "results" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("safesMultisigTransactionsListOK" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *SafesMultisigTransactionsListOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SafesMultisigTransactionsListOKBody) UnmarshalBinary(b []byte) error {
	var res SafesMultisigTransactionsListOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
