// Code generated by go-swagger; DO NOT EDIT.

package safes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MoonSHRD/dao-tg/pkg/gnosis/models"
)

// SafesBalancesUsdListReader is a Reader for the SafesBalancesUsdList structure.
type SafesBalancesUsdListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SafesBalancesUsdListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSafesBalancesUsdListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewSafesBalancesUsdListNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewSafesBalancesUsdListUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSafesBalancesUsdListOK creates a SafesBalancesUsdListOK with default headers values
func NewSafesBalancesUsdListOK() *SafesBalancesUsdListOK {
	return &SafesBalancesUsdListOK{}
}

/* SafesBalancesUsdListOK describes a response with status code 200, with default header values.

SafesBalancesUsdListOK safes balances usd list o k
*/
type SafesBalancesUsdListOK struct {
	Payload []*models.SafeBalanceUsdResponse
}

func (o *SafesBalancesUsdListOK) Error() string {
	return fmt.Sprintf("[GET /safes/{address}/balances/usd/][%d] safesBalancesUsdListOK  %+v", 200, o.Payload)
}
func (o *SafesBalancesUsdListOK) GetPayload() []*models.SafeBalanceUsdResponse {
	return o.Payload
}

func (o *SafesBalancesUsdListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSafesBalancesUsdListNotFound creates a SafesBalancesUsdListNotFound with default headers values
func NewSafesBalancesUsdListNotFound() *SafesBalancesUsdListNotFound {
	return &SafesBalancesUsdListNotFound{}
}

/* SafesBalancesUsdListNotFound describes a response with status code 404, with default header values.

Safe not found
*/
type SafesBalancesUsdListNotFound struct {
}

func (o *SafesBalancesUsdListNotFound) Error() string {
	return fmt.Sprintf("[GET /safes/{address}/balances/usd/][%d] safesBalancesUsdListNotFound ", 404)
}

func (o *SafesBalancesUsdListNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSafesBalancesUsdListUnprocessableEntity creates a SafesBalancesUsdListUnprocessableEntity with default headers values
func NewSafesBalancesUsdListUnprocessableEntity() *SafesBalancesUsdListUnprocessableEntity {
	return &SafesBalancesUsdListUnprocessableEntity{}
}

/* SafesBalancesUsdListUnprocessableEntity describes a response with status code 422, with default header values.

Safe address checksum not valid
*/
type SafesBalancesUsdListUnprocessableEntity struct {
}

func (o *SafesBalancesUsdListUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /safes/{address}/balances/usd/][%d] safesBalancesUsdListUnprocessableEntity ", 422)
}

func (o *SafesBalancesUsdListUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
