// Code generated by go-swagger; DO NOT EDIT.

package safes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/MoonSHRD/dao-tg/pkg/gnosis/models"
)

// NewSafesMultisigTransactionsCreateParams creates a new SafesMultisigTransactionsCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSafesMultisigTransactionsCreateParams() *SafesMultisigTransactionsCreateParams {
	return &SafesMultisigTransactionsCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSafesMultisigTransactionsCreateParamsWithTimeout creates a new SafesMultisigTransactionsCreateParams object
// with the ability to set a timeout on a request.
func NewSafesMultisigTransactionsCreateParamsWithTimeout(timeout time.Duration) *SafesMultisigTransactionsCreateParams {
	return &SafesMultisigTransactionsCreateParams{
		timeout: timeout,
	}
}

// NewSafesMultisigTransactionsCreateParamsWithContext creates a new SafesMultisigTransactionsCreateParams object
// with the ability to set a context for a request.
func NewSafesMultisigTransactionsCreateParamsWithContext(ctx context.Context) *SafesMultisigTransactionsCreateParams {
	return &SafesMultisigTransactionsCreateParams{
		Context: ctx,
	}
}

// NewSafesMultisigTransactionsCreateParamsWithHTTPClient creates a new SafesMultisigTransactionsCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewSafesMultisigTransactionsCreateParamsWithHTTPClient(client *http.Client) *SafesMultisigTransactionsCreateParams {
	return &SafesMultisigTransactionsCreateParams{
		HTTPClient: client,
	}
}

/* SafesMultisigTransactionsCreateParams contains all the parameters to send to the API endpoint
   for the safes multisig transactions create operation.

   Typically these are written to a http.Request.
*/
type SafesMultisigTransactionsCreateParams struct {

	// Address.
	Address string

	// Data.
	Data *models.SafeMultisigTransaction

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the safes multisig transactions create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SafesMultisigTransactionsCreateParams) WithDefaults() *SafesMultisigTransactionsCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the safes multisig transactions create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SafesMultisigTransactionsCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the safes multisig transactions create params
func (o *SafesMultisigTransactionsCreateParams) WithTimeout(timeout time.Duration) *SafesMultisigTransactionsCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the safes multisig transactions create params
func (o *SafesMultisigTransactionsCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the safes multisig transactions create params
func (o *SafesMultisigTransactionsCreateParams) WithContext(ctx context.Context) *SafesMultisigTransactionsCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the safes multisig transactions create params
func (o *SafesMultisigTransactionsCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the safes multisig transactions create params
func (o *SafesMultisigTransactionsCreateParams) WithHTTPClient(client *http.Client) *SafesMultisigTransactionsCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the safes multisig transactions create params
func (o *SafesMultisigTransactionsCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the safes multisig transactions create params
func (o *SafesMultisigTransactionsCreateParams) WithAddress(address string) *SafesMultisigTransactionsCreateParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the safes multisig transactions create params
func (o *SafesMultisigTransactionsCreateParams) SetAddress(address string) {
	o.Address = address
}

// WithData adds the data to the safes multisig transactions create params
func (o *SafesMultisigTransactionsCreateParams) WithData(data *models.SafeMultisigTransaction) *SafesMultisigTransactionsCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the safes multisig transactions create params
func (o *SafesMultisigTransactionsCreateParams) SetData(data *models.SafeMultisigTransaction) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *SafesMultisigTransactionsCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param address
	if err := r.SetPathParam("address", o.Address); err != nil {
		return err
	}
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
