// Code generated by go-swagger; DO NOT EDIT.

package safes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MoonSHRD/dao-tg/pkg/gnosis/models"
)

// SafesAllTransactionsListReader is a Reader for the SafesAllTransactionsList structure.
type SafesAllTransactionsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SafesAllTransactionsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSafesAllTransactionsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewSafesAllTransactionsListUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSafesAllTransactionsListOK creates a SafesAllTransactionsListOK with default headers values
func NewSafesAllTransactionsListOK() *SafesAllTransactionsListOK {
	return &SafesAllTransactionsListOK{}
}

/* SafesAllTransactionsListOK describes a response with status code 200, with default header values.

A list with every element with the structure of one of these transactiontypes
*/
type SafesAllTransactionsListOK struct {
	Payload *models.AllTransactionsSchema
}

func (o *SafesAllTransactionsListOK) Error() string {
	return fmt.Sprintf("[GET /safes/{address}/all-transactions/][%d] safesAllTransactionsListOK  %+v", 200, o.Payload)
}
func (o *SafesAllTransactionsListOK) GetPayload() *models.AllTransactionsSchema {
	return o.Payload
}

func (o *SafesAllTransactionsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AllTransactionsSchema)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSafesAllTransactionsListUnprocessableEntity creates a SafesAllTransactionsListUnprocessableEntity with default headers values
func NewSafesAllTransactionsListUnprocessableEntity() *SafesAllTransactionsListUnprocessableEntity {
	return &SafesAllTransactionsListUnprocessableEntity{}
}

/* SafesAllTransactionsListUnprocessableEntity describes a response with status code 422, with default header values.

code = 1: Checksum address validation failed
*/
type SafesAllTransactionsListUnprocessableEntity struct {
}

func (o *SafesAllTransactionsListUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /safes/{address}/all-transactions/][%d] safesAllTransactionsListUnprocessableEntity ", 422)
}

func (o *SafesAllTransactionsListUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
