// Code generated by go-swagger; DO NOT EDIT.

package safes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/MoonSHRD/dao-tg/pkg/gnosis/models"
)

// SafesModuleTransactionsListReader is a Reader for the SafesModuleTransactionsList structure.
type SafesModuleTransactionsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SafesModuleTransactionsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSafesModuleTransactionsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSafesModuleTransactionsListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewSafesModuleTransactionsListUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSafesModuleTransactionsListOK creates a SafesModuleTransactionsListOK with default headers values
func NewSafesModuleTransactionsListOK() *SafesModuleTransactionsListOK {
	return &SafesModuleTransactionsListOK{}
}

/* SafesModuleTransactionsListOK describes a response with status code 200, with default header values.

SafesModuleTransactionsListOK safes module transactions list o k
*/
type SafesModuleTransactionsListOK struct {
	Payload *SafesModuleTransactionsListOKBody
}

func (o *SafesModuleTransactionsListOK) Error() string {
	return fmt.Sprintf("[GET /safes/{address}/module-transactions/][%d] safesModuleTransactionsListOK  %+v", 200, o.Payload)
}
func (o *SafesModuleTransactionsListOK) GetPayload() *SafesModuleTransactionsListOKBody {
	return o.Payload
}

func (o *SafesModuleTransactionsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SafesModuleTransactionsListOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSafesModuleTransactionsListBadRequest creates a SafesModuleTransactionsListBadRequest with default headers values
func NewSafesModuleTransactionsListBadRequest() *SafesModuleTransactionsListBadRequest {
	return &SafesModuleTransactionsListBadRequest{}
}

/* SafesModuleTransactionsListBadRequest describes a response with status code 400, with default header values.

Invalid data
*/
type SafesModuleTransactionsListBadRequest struct {
}

func (o *SafesModuleTransactionsListBadRequest) Error() string {
	return fmt.Sprintf("[GET /safes/{address}/module-transactions/][%d] safesModuleTransactionsListBadRequest ", 400)
}

func (o *SafesModuleTransactionsListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSafesModuleTransactionsListUnprocessableEntity creates a SafesModuleTransactionsListUnprocessableEntity with default headers values
func NewSafesModuleTransactionsListUnprocessableEntity() *SafesModuleTransactionsListUnprocessableEntity {
	return &SafesModuleTransactionsListUnprocessableEntity{}
}

/* SafesModuleTransactionsListUnprocessableEntity describes a response with status code 422, with default header values.

Invalid ethereum address
*/
type SafesModuleTransactionsListUnprocessableEntity struct {
}

func (o *SafesModuleTransactionsListUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /safes/{address}/module-transactions/][%d] safesModuleTransactionsListUnprocessableEntity ", 422)
}

func (o *SafesModuleTransactionsListUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*SafesModuleTransactionsListOKBody safes module transactions list o k body
swagger:model SafesModuleTransactionsListOKBody
*/
type SafesModuleTransactionsListOKBody struct {

	// count
	// Required: true
	Count *int64 `json:"count"`

	// next
	// Format: uri
	Next *strfmt.URI `json:"next,omitempty"`

	// previous
	// Format: uri
	Previous *strfmt.URI `json:"previous,omitempty"`

	// results
	// Required: true
	Results []*models.SafeModuleTransactionResponse `json:"results"`
}

// Validate validates this safes module transactions list o k body
func (o *SafesModuleTransactionsListOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCount(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateNext(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePrevious(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateResults(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SafesModuleTransactionsListOKBody) validateCount(formats strfmt.Registry) error {

	if err := validate.Required("safesModuleTransactionsListOK"+"."+"count", "body", o.Count); err != nil {
		return err
	}

	return nil
}

func (o *SafesModuleTransactionsListOKBody) validateNext(formats strfmt.Registry) error {
	if swag.IsZero(o.Next) { // not required
		return nil
	}

	if err := validate.FormatOf("safesModuleTransactionsListOK"+"."+"next", "body", "uri", o.Next.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *SafesModuleTransactionsListOKBody) validatePrevious(formats strfmt.Registry) error {
	if swag.IsZero(o.Previous) { // not required
		return nil
	}

	if err := validate.FormatOf("safesModuleTransactionsListOK"+"."+"previous", "body", "uri", o.Previous.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *SafesModuleTransactionsListOKBody) validateResults(formats strfmt.Registry) error {

	if err := validate.Required("safesModuleTransactionsListOK"+"."+"results", "body", o.Results); err != nil {
		return err
	}

	for i := 0; i < len(o.Results); i++ {
		if swag.IsZero(o.Results[i]) { // not required
			continue
		}

		if o.Results[i] != nil {
			if err := o.Results[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("safesModuleTransactionsListOK" + "." + "results" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("safesModuleTransactionsListOK" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this safes module transactions list o k body based on the context it is used
func (o *SafesModuleTransactionsListOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResults(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SafesModuleTransactionsListOKBody) contextValidateResults(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Results); i++ {

		if o.Results[i] != nil {
			if err := o.Results[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("safesModuleTransactionsListOK" + "." + "results" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("safesModuleTransactionsListOK" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *SafesModuleTransactionsListOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SafesModuleTransactionsListOKBody) UnmarshalBinary(b []byte) error {
	var res SafesModuleTransactionsListOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
