// Code generated by go-swagger; DO NOT EDIT.

package safes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MoonSHRD/dao-tg/pkg/gnosis/models"
)

// SafesBalancesListReader is a Reader for the SafesBalancesList structure.
type SafesBalancesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SafesBalancesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSafesBalancesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewSafesBalancesListNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewSafesBalancesListUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSafesBalancesListOK creates a SafesBalancesListOK with default headers values
func NewSafesBalancesListOK() *SafesBalancesListOK {
	return &SafesBalancesListOK{}
}

/* SafesBalancesListOK describes a response with status code 200, with default header values.

SafesBalancesListOK safes balances list o k
*/
type SafesBalancesListOK struct {
	Payload []*models.SafeBalanceResponse
}

func (o *SafesBalancesListOK) Error() string {
	return fmt.Sprintf("[GET /safes/{address}/balances/][%d] safesBalancesListOK  %+v", 200, o.Payload)
}
func (o *SafesBalancesListOK) GetPayload() []*models.SafeBalanceResponse {
	return o.Payload
}

func (o *SafesBalancesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSafesBalancesListNotFound creates a SafesBalancesListNotFound with default headers values
func NewSafesBalancesListNotFound() *SafesBalancesListNotFound {
	return &SafesBalancesListNotFound{}
}

/* SafesBalancesListNotFound describes a response with status code 404, with default header values.

Safe not found
*/
type SafesBalancesListNotFound struct {
}

func (o *SafesBalancesListNotFound) Error() string {
	return fmt.Sprintf("[GET /safes/{address}/balances/][%d] safesBalancesListNotFound ", 404)
}

func (o *SafesBalancesListNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSafesBalancesListUnprocessableEntity creates a SafesBalancesListUnprocessableEntity with default headers values
func NewSafesBalancesListUnprocessableEntity() *SafesBalancesListUnprocessableEntity {
	return &SafesBalancesListUnprocessableEntity{}
}

/* SafesBalancesListUnprocessableEntity describes a response with status code 422, with default header values.

Safe address checksum not valid
*/
type SafesBalancesListUnprocessableEntity struct {
}

func (o *SafesBalancesListUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /safes/{address}/balances/][%d] safesBalancesListUnprocessableEntity ", 422)
}

func (o *SafesBalancesListUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
