// Code generated by go-swagger; DO NOT EDIT.

package delegates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDelegatesListParams creates a new DelegatesListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDelegatesListParams() *DelegatesListParams {
	return &DelegatesListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDelegatesListParamsWithTimeout creates a new DelegatesListParams object
// with the ability to set a timeout on a request.
func NewDelegatesListParamsWithTimeout(timeout time.Duration) *DelegatesListParams {
	return &DelegatesListParams{
		timeout: timeout,
	}
}

// NewDelegatesListParamsWithContext creates a new DelegatesListParams object
// with the ability to set a context for a request.
func NewDelegatesListParamsWithContext(ctx context.Context) *DelegatesListParams {
	return &DelegatesListParams{
		Context: ctx,
	}
}

// NewDelegatesListParamsWithHTTPClient creates a new DelegatesListParams object
// with the ability to set a custom HTTPClient for a request.
func NewDelegatesListParamsWithHTTPClient(client *http.Client) *DelegatesListParams {
	return &DelegatesListParams{
		HTTPClient: client,
	}
}

/* DelegatesListParams contains all the parameters to send to the API endpoint
   for the delegates list operation.

   Typically these are written to a http.Request.
*/
type DelegatesListParams struct {

	// Delegate.
	Delegate *string

	// Delegator.
	Delegator *string

	// Label.
	Label *string

	/* Limit.

	   Number of results to return per page.
	*/
	Limit *int64

	/* Offset.

	   The initial index from which to return the results.
	*/
	Offset *int64

	// Safe.
	Safe *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delegates list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DelegatesListParams) WithDefaults() *DelegatesListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delegates list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DelegatesListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delegates list params
func (o *DelegatesListParams) WithTimeout(timeout time.Duration) *DelegatesListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delegates list params
func (o *DelegatesListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delegates list params
func (o *DelegatesListParams) WithContext(ctx context.Context) *DelegatesListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delegates list params
func (o *DelegatesListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delegates list params
func (o *DelegatesListParams) WithHTTPClient(client *http.Client) *DelegatesListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delegates list params
func (o *DelegatesListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDelegate adds the delegate to the delegates list params
func (o *DelegatesListParams) WithDelegate(delegate *string) *DelegatesListParams {
	o.SetDelegate(delegate)
	return o
}

// SetDelegate adds the delegate to the delegates list params
func (o *DelegatesListParams) SetDelegate(delegate *string) {
	o.Delegate = delegate
}

// WithDelegator adds the delegator to the delegates list params
func (o *DelegatesListParams) WithDelegator(delegator *string) *DelegatesListParams {
	o.SetDelegator(delegator)
	return o
}

// SetDelegator adds the delegator to the delegates list params
func (o *DelegatesListParams) SetDelegator(delegator *string) {
	o.Delegator = delegator
}

// WithLabel adds the label to the delegates list params
func (o *DelegatesListParams) WithLabel(label *string) *DelegatesListParams {
	o.SetLabel(label)
	return o
}

// SetLabel adds the label to the delegates list params
func (o *DelegatesListParams) SetLabel(label *string) {
	o.Label = label
}

// WithLimit adds the limit to the delegates list params
func (o *DelegatesListParams) WithLimit(limit *int64) *DelegatesListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the delegates list params
func (o *DelegatesListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the delegates list params
func (o *DelegatesListParams) WithOffset(offset *int64) *DelegatesListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the delegates list params
func (o *DelegatesListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithSafe adds the safe to the delegates list params
func (o *DelegatesListParams) WithSafe(safe *string) *DelegatesListParams {
	o.SetSafe(safe)
	return o
}

// SetSafe adds the safe to the delegates list params
func (o *DelegatesListParams) SetSafe(safe *string) {
	o.Safe = safe
}

// WriteToRequest writes these params to a swagger request
func (o *DelegatesListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Delegate != nil {

		// query param delegate
		var qrDelegate string

		if o.Delegate != nil {
			qrDelegate = *o.Delegate
		}
		qDelegate := qrDelegate
		if qDelegate != "" {

			if err := r.SetQueryParam("delegate", qDelegate); err != nil {
				return err
			}
		}
	}

	if o.Delegator != nil {

		// query param delegator
		var qrDelegator string

		if o.Delegator != nil {
			qrDelegator = *o.Delegator
		}
		qDelegator := qrDelegator
		if qDelegator != "" {

			if err := r.SetQueryParam("delegator", qDelegator); err != nil {
				return err
			}
		}
	}

	if o.Label != nil {

		// query param label
		var qrLabel string

		if o.Label != nil {
			qrLabel = *o.Label
		}
		qLabel := qrLabel
		if qLabel != "" {

			if err := r.SetQueryParam("label", qLabel); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Safe != nil {

		// query param safe
		var qrSafe string

		if o.Safe != nil {
			qrSafe = *o.Safe
		}
		qSafe := qrSafe
		if qSafe != "" {

			if err := r.SetQueryParam("safe", qSafe); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
