// Code generated by go-swagger; DO NOT EDIT.

package delegates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/MoonSHRD/dao-tg/pkg/gnosis/models"
)

// NewDelegatesDeleteParams creates a new DelegatesDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDelegatesDeleteParams() *DelegatesDeleteParams {
	return &DelegatesDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDelegatesDeleteParamsWithTimeout creates a new DelegatesDeleteParams object
// with the ability to set a timeout on a request.
func NewDelegatesDeleteParamsWithTimeout(timeout time.Duration) *DelegatesDeleteParams {
	return &DelegatesDeleteParams{
		timeout: timeout,
	}
}

// NewDelegatesDeleteParamsWithContext creates a new DelegatesDeleteParams object
// with the ability to set a context for a request.
func NewDelegatesDeleteParamsWithContext(ctx context.Context) *DelegatesDeleteParams {
	return &DelegatesDeleteParams{
		Context: ctx,
	}
}

// NewDelegatesDeleteParamsWithHTTPClient creates a new DelegatesDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewDelegatesDeleteParamsWithHTTPClient(client *http.Client) *DelegatesDeleteParams {
	return &DelegatesDeleteParams{
		HTTPClient: client,
	}
}

/* DelegatesDeleteParams contains all the parameters to send to the API endpoint
   for the delegates delete operation.

   Typically these are written to a http.Request.
*/
type DelegatesDeleteParams struct {

	// Data.
	Data *models.DelegateDelete

	// DelegateAddress.
	DelegateAddress string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delegates delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DelegatesDeleteParams) WithDefaults() *DelegatesDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delegates delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DelegatesDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delegates delete params
func (o *DelegatesDeleteParams) WithTimeout(timeout time.Duration) *DelegatesDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delegates delete params
func (o *DelegatesDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delegates delete params
func (o *DelegatesDeleteParams) WithContext(ctx context.Context) *DelegatesDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delegates delete params
func (o *DelegatesDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delegates delete params
func (o *DelegatesDeleteParams) WithHTTPClient(client *http.Client) *DelegatesDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delegates delete params
func (o *DelegatesDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the delegates delete params
func (o *DelegatesDeleteParams) WithData(data *models.DelegateDelete) *DelegatesDeleteParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the delegates delete params
func (o *DelegatesDeleteParams) SetData(data *models.DelegateDelete) {
	o.Data = data
}

// WithDelegateAddress adds the delegateAddress to the delegates delete params
func (o *DelegatesDeleteParams) WithDelegateAddress(delegateAddress string) *DelegatesDeleteParams {
	o.SetDelegateAddress(delegateAddress)
	return o
}

// SetDelegateAddress adds the delegateAddress to the delegates delete params
func (o *DelegatesDeleteParams) SetDelegateAddress(delegateAddress string) {
	o.DelegateAddress = delegateAddress
}

// WriteToRequest writes these params to a swagger request
func (o *DelegatesDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param delegate_address
	if err := r.SetPathParam("delegate_address", o.DelegateAddress); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
