// Code generated by go-swagger; DO NOT EDIT.

package delegates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DelegatesCreateReader is a Reader for the DelegatesCreate structure.
type DelegatesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DelegatesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewDelegatesCreateAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDelegatesCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDelegatesCreateAccepted creates a DelegatesCreateAccepted with default headers values
func NewDelegatesCreateAccepted() *DelegatesCreateAccepted {
	return &DelegatesCreateAccepted{}
}

/* DelegatesCreateAccepted describes a response with status code 202, with default header values.

Accepted
*/
type DelegatesCreateAccepted struct {
}

func (o *DelegatesCreateAccepted) Error() string {
	return fmt.Sprintf("[POST /delegates/][%d] delegatesCreateAccepted ", 202)
}

func (o *DelegatesCreateAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDelegatesCreateBadRequest creates a DelegatesCreateBadRequest with default headers values
func NewDelegatesCreateBadRequest() *DelegatesCreateBadRequest {
	return &DelegatesCreateBadRequest{}
}

/* DelegatesCreateBadRequest describes a response with status code 400, with default header values.

Malformed data
*/
type DelegatesCreateBadRequest struct {
}

func (o *DelegatesCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /delegates/][%d] delegatesCreateBadRequest ", 400)
}

func (o *DelegatesCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
