// Code generated by go-swagger; DO NOT EDIT.

package analytics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/MoonSHRD/dao-tg/pkg/gnosis/models"
)

// AnalyticsMultisigTransactionsBySafeListReader is a Reader for the AnalyticsMultisigTransactionsBySafeList structure.
type AnalyticsMultisigTransactionsBySafeListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AnalyticsMultisigTransactionsBySafeListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAnalyticsMultisigTransactionsBySafeListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAnalyticsMultisigTransactionsBySafeListOK creates a AnalyticsMultisigTransactionsBySafeListOK with default headers values
func NewAnalyticsMultisigTransactionsBySafeListOK() *AnalyticsMultisigTransactionsBySafeListOK {
	return &AnalyticsMultisigTransactionsBySafeListOK{}
}

/* AnalyticsMultisigTransactionsBySafeListOK describes a response with status code 200, with default header values.

AnalyticsMultisigTransactionsBySafeListOK analytics multisig transactions by safe list o k
*/
type AnalyticsMultisigTransactionsBySafeListOK struct {
	Payload *AnalyticsMultisigTransactionsBySafeListOKBody
}

func (o *AnalyticsMultisigTransactionsBySafeListOK) Error() string {
	return fmt.Sprintf("[GET /analytics/multisig-transactions/by-safe/][%d] analyticsMultisigTransactionsBySafeListOK  %+v", 200, o.Payload)
}
func (o *AnalyticsMultisigTransactionsBySafeListOK) GetPayload() *AnalyticsMultisigTransactionsBySafeListOKBody {
	return o.Payload
}

func (o *AnalyticsMultisigTransactionsBySafeListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(AnalyticsMultisigTransactionsBySafeListOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*AnalyticsMultisigTransactionsBySafeListOKBody analytics multisig transactions by safe list o k body
swagger:model AnalyticsMultisigTransactionsBySafeListOKBody
*/
type AnalyticsMultisigTransactionsBySafeListOKBody struct {

	// count
	// Required: true
	Count *int64 `json:"count"`

	// next
	// Format: uri
	Next *strfmt.URI `json:"next,omitempty"`

	// previous
	// Format: uri
	Previous *strfmt.URI `json:"previous,omitempty"`

	// results
	// Required: true
	Results []*models.AnalyticsMultisigTxsBySafeResponse `json:"results"`
}

// Validate validates this analytics multisig transactions by safe list o k body
func (o *AnalyticsMultisigTransactionsBySafeListOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateCount(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateNext(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePrevious(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateResults(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AnalyticsMultisigTransactionsBySafeListOKBody) validateCount(formats strfmt.Registry) error {

	if err := validate.Required("analyticsMultisigTransactionsBySafeListOK"+"."+"count", "body", o.Count); err != nil {
		return err
	}

	return nil
}

func (o *AnalyticsMultisigTransactionsBySafeListOKBody) validateNext(formats strfmt.Registry) error {
	if swag.IsZero(o.Next) { // not required
		return nil
	}

	if err := validate.FormatOf("analyticsMultisigTransactionsBySafeListOK"+"."+"next", "body", "uri", o.Next.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *AnalyticsMultisigTransactionsBySafeListOKBody) validatePrevious(formats strfmt.Registry) error {
	if swag.IsZero(o.Previous) { // not required
		return nil
	}

	if err := validate.FormatOf("analyticsMultisigTransactionsBySafeListOK"+"."+"previous", "body", "uri", o.Previous.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *AnalyticsMultisigTransactionsBySafeListOKBody) validateResults(formats strfmt.Registry) error {

	if err := validate.Required("analyticsMultisigTransactionsBySafeListOK"+"."+"results", "body", o.Results); err != nil {
		return err
	}

	for i := 0; i < len(o.Results); i++ {
		if swag.IsZero(o.Results[i]) { // not required
			continue
		}

		if o.Results[i] != nil {
			if err := o.Results[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("analyticsMultisigTransactionsBySafeListOK" + "." + "results" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("analyticsMultisigTransactionsBySafeListOK" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this analytics multisig transactions by safe list o k body based on the context it is used
func (o *AnalyticsMultisigTransactionsBySafeListOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateResults(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AnalyticsMultisigTransactionsBySafeListOKBody) contextValidateResults(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Results); i++ {

		if o.Results[i] != nil {
			if err := o.Results[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("analyticsMultisigTransactionsBySafeListOK" + "." + "results" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("analyticsMultisigTransactionsBySafeListOK" + "." + "results" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *AnalyticsMultisigTransactionsBySafeListOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AnalyticsMultisigTransactionsBySafeListOKBody) UnmarshalBinary(b []byte) error {
	var res AnalyticsMultisigTransactionsBySafeListOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
