// Code generated by go-swagger; DO NOT EDIT.

package tokens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewTokensPricesUsdListParams creates a new TokensPricesUsdListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTokensPricesUsdListParams() *TokensPricesUsdListParams {
	return &TokensPricesUsdListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTokensPricesUsdListParamsWithTimeout creates a new TokensPricesUsdListParams object
// with the ability to set a timeout on a request.
func NewTokensPricesUsdListParamsWithTimeout(timeout time.Duration) *TokensPricesUsdListParams {
	return &TokensPricesUsdListParams{
		timeout: timeout,
	}
}

// NewTokensPricesUsdListParamsWithContext creates a new TokensPricesUsdListParams object
// with the ability to set a context for a request.
func NewTokensPricesUsdListParamsWithContext(ctx context.Context) *TokensPricesUsdListParams {
	return &TokensPricesUsdListParams{
		Context: ctx,
	}
}

// NewTokensPricesUsdListParamsWithHTTPClient creates a new TokensPricesUsdListParams object
// with the ability to set a custom HTTPClient for a request.
func NewTokensPricesUsdListParamsWithHTTPClient(client *http.Client) *TokensPricesUsdListParams {
	return &TokensPricesUsdListParams{
		HTTPClient: client,
	}
}

/* TokensPricesUsdListParams contains all the parameters to send to the API endpoint
   for the tokens prices usd list operation.

   Typically these are written to a http.Request.
*/
type TokensPricesUsdListParams struct {

	/* Address.

	   A unique value identifying this token.
	*/
	Address string

	/* Limit.

	   Number of results to return per page.
	*/
	Limit *int64

	/* Offset.

	   The initial index from which to return the results.
	*/
	Offset *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the tokens prices usd list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TokensPricesUsdListParams) WithDefaults() *TokensPricesUsdListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the tokens prices usd list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TokensPricesUsdListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the tokens prices usd list params
func (o *TokensPricesUsdListParams) WithTimeout(timeout time.Duration) *TokensPricesUsdListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the tokens prices usd list params
func (o *TokensPricesUsdListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the tokens prices usd list params
func (o *TokensPricesUsdListParams) WithContext(ctx context.Context) *TokensPricesUsdListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the tokens prices usd list params
func (o *TokensPricesUsdListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the tokens prices usd list params
func (o *TokensPricesUsdListParams) WithHTTPClient(client *http.Client) *TokensPricesUsdListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the tokens prices usd list params
func (o *TokensPricesUsdListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the tokens prices usd list params
func (o *TokensPricesUsdListParams) WithAddress(address string) *TokensPricesUsdListParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the tokens prices usd list params
func (o *TokensPricesUsdListParams) SetAddress(address string) {
	o.Address = address
}

// WithLimit adds the limit to the tokens prices usd list params
func (o *TokensPricesUsdListParams) WithLimit(limit *int64) *TokensPricesUsdListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the tokens prices usd list params
func (o *TokensPricesUsdListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the tokens prices usd list params
func (o *TokensPricesUsdListParams) WithOffset(offset *int64) *TokensPricesUsdListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the tokens prices usd list params
func (o *TokensPricesUsdListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *TokensPricesUsdListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param address
	if err := r.SetPathParam("address", o.Address); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
