// Code generated by go-swagger; DO NOT EDIT.

package tokens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTokensReadParams creates a new TokensReadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTokensReadParams() *TokensReadParams {
	return &TokensReadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTokensReadParamsWithTimeout creates a new TokensReadParams object
// with the ability to set a timeout on a request.
func NewTokensReadParamsWithTimeout(timeout time.Duration) *TokensReadParams {
	return &TokensReadParams{
		timeout: timeout,
	}
}

// NewTokensReadParamsWithContext creates a new TokensReadParams object
// with the ability to set a context for a request.
func NewTokensReadParamsWithContext(ctx context.Context) *TokensReadParams {
	return &TokensReadParams{
		Context: ctx,
	}
}

// NewTokensReadParamsWithHTTPClient creates a new TokensReadParams object
// with the ability to set a custom HTTPClient for a request.
func NewTokensReadParamsWithHTTPClient(client *http.Client) *TokensReadParams {
	return &TokensReadParams{
		HTTPClient: client,
	}
}

/* TokensReadParams contains all the parameters to send to the API endpoint
   for the tokens read operation.

   Typically these are written to a http.Request.
*/
type TokensReadParams struct {

	/* Address.

	   A unique value identifying this token.
	*/
	Address string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the tokens read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TokensReadParams) WithDefaults() *TokensReadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the tokens read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TokensReadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the tokens read params
func (o *TokensReadParams) WithTimeout(timeout time.Duration) *TokensReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the tokens read params
func (o *TokensReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the tokens read params
func (o *TokensReadParams) WithContext(ctx context.Context) *TokensReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the tokens read params
func (o *TokensReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the tokens read params
func (o *TokensReadParams) WithHTTPClient(client *http.Client) *TokensReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the tokens read params
func (o *TokensReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the tokens read params
func (o *TokensReadParams) WithAddress(address string) *TokensReadParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the tokens read params
func (o *TokensReadParams) SetAddress(address string) {
	o.Address = address
}

// WriteToRequest writes these params to a swagger request
func (o *TokensReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param address
	if err := r.SetPathParam("address", o.Address); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
