// Code generated by go-swagger; DO NOT EDIT.

package owners

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MoonSHRD/dao-tg/pkg/gnosis/models"
)

// OwnersSafesListReader is a Reader for the OwnersSafesList structure.
type OwnersSafesListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OwnersSafesListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOwnersSafesListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewOwnersSafesListUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOwnersSafesListOK creates a OwnersSafesListOK with default headers values
func NewOwnersSafesListOK() *OwnersSafesListOK {
	return &OwnersSafesListOK{}
}

/* OwnersSafesListOK describes a response with status code 200, with default header values.

OwnersSafesListOK owners safes list o k
*/
type OwnersSafesListOK struct {
	Payload *models.OwnerResponse
}

func (o *OwnersSafesListOK) Error() string {
	return fmt.Sprintf("[GET /owners/{address}/safes/][%d] ownersSafesListOK  %+v", 200, o.Payload)
}
func (o *OwnersSafesListOK) GetPayload() *models.OwnerResponse {
	return o.Payload
}

func (o *OwnersSafesListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OwnerResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOwnersSafesListUnprocessableEntity creates a OwnersSafesListUnprocessableEntity with default headers values
func NewOwnersSafesListUnprocessableEntity() *OwnersSafesListUnprocessableEntity {
	return &OwnersSafesListUnprocessableEntity{}
}

/* OwnersSafesListUnprocessableEntity describes a response with status code 422, with default header values.

Owner address checksum not valid
*/
type OwnersSafesListUnprocessableEntity struct {
}

func (o *OwnersSafesListUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /owners/{address}/safes/][%d] ownersSafesListUnprocessableEntity ", 422)
}

func (o *OwnersSafesListUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
