// Code generated by go-swagger; DO NOT EDIT.

package notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/MoonSHRD/dao-tg/pkg/gnosis/models"
)

// NewNotificationsDevicesCreateParams creates a new NotificationsDevicesCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewNotificationsDevicesCreateParams() *NotificationsDevicesCreateParams {
	return &NotificationsDevicesCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewNotificationsDevicesCreateParamsWithTimeout creates a new NotificationsDevicesCreateParams object
// with the ability to set a timeout on a request.
func NewNotificationsDevicesCreateParamsWithTimeout(timeout time.Duration) *NotificationsDevicesCreateParams {
	return &NotificationsDevicesCreateParams{
		timeout: timeout,
	}
}

// NewNotificationsDevicesCreateParamsWithContext creates a new NotificationsDevicesCreateParams object
// with the ability to set a context for a request.
func NewNotificationsDevicesCreateParamsWithContext(ctx context.Context) *NotificationsDevicesCreateParams {
	return &NotificationsDevicesCreateParams{
		Context: ctx,
	}
}

// NewNotificationsDevicesCreateParamsWithHTTPClient creates a new NotificationsDevicesCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewNotificationsDevicesCreateParamsWithHTTPClient(client *http.Client) *NotificationsDevicesCreateParams {
	return &NotificationsDevicesCreateParams{
		HTTPClient: client,
	}
}

/* NotificationsDevicesCreateParams contains all the parameters to send to the API endpoint
   for the notifications devices create operation.

   Typically these are written to a http.Request.
*/
type NotificationsDevicesCreateParams struct {

	// Data.
	Data *models.FirebaseDevice

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the notifications devices create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NotificationsDevicesCreateParams) WithDefaults() *NotificationsDevicesCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the notifications devices create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NotificationsDevicesCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the notifications devices create params
func (o *NotificationsDevicesCreateParams) WithTimeout(timeout time.Duration) *NotificationsDevicesCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the notifications devices create params
func (o *NotificationsDevicesCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the notifications devices create params
func (o *NotificationsDevicesCreateParams) WithContext(ctx context.Context) *NotificationsDevicesCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the notifications devices create params
func (o *NotificationsDevicesCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the notifications devices create params
func (o *NotificationsDevicesCreateParams) WithHTTPClient(client *http.Client) *NotificationsDevicesCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the notifications devices create params
func (o *NotificationsDevicesCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the notifications devices create params
func (o *NotificationsDevicesCreateParams) WithData(data *models.FirebaseDevice) *NotificationsDevicesCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the notifications devices create params
func (o *NotificationsDevicesCreateParams) SetData(data *models.FirebaseDevice) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *NotificationsDevicesCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
