// Code generated by go-swagger; DO NOT EDIT.

package notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// NotificationsDevicesDeleteReader is a Reader for the NotificationsDevicesDelete structure.
type NotificationsDevicesDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NotificationsDevicesDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewNotificationsDevicesDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewNotificationsDevicesDeleteNoContent creates a NotificationsDevicesDeleteNoContent with default headers values
func NewNotificationsDevicesDeleteNoContent() *NotificationsDevicesDeleteNoContent {
	return &NotificationsDevicesDeleteNoContent{}
}

/* NotificationsDevicesDeleteNoContent describes a response with status code 204, with default header values.

NotificationsDevicesDeleteNoContent notifications devices delete no content
*/
type NotificationsDevicesDeleteNoContent struct {
}

func (o *NotificationsDevicesDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /notifications/devices/{uuid}/][%d] notificationsDevicesDeleteNoContent ", 204)
}

func (o *NotificationsDevicesDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
