// Code generated by go-swagger; DO NOT EDIT.

package notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// NotificationsDevicesSafesDeleteReader is a Reader for the NotificationsDevicesSafesDelete structure.
type NotificationsDevicesSafesDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NotificationsDevicesSafesDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewNotificationsDevicesSafesDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewNotificationsDevicesSafesDeleteNoContent creates a NotificationsDevicesSafesDeleteNoContent with default headers values
func NewNotificationsDevicesSafesDeleteNoContent() *NotificationsDevicesSafesDeleteNoContent {
	return &NotificationsDevicesSafesDeleteNoContent{}
}

/* NotificationsDevicesSafesDeleteNoContent describes a response with status code 204, with default header values.

NotificationsDevicesSafesDeleteNoContent notifications devices safes delete no content
*/
type NotificationsDevicesSafesDeleteNoContent struct {
}

func (o *NotificationsDevicesSafesDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /notifications/devices/{uuid}/safes/{address}/][%d] notificationsDevicesSafesDeleteNoContent ", 204)
}

func (o *NotificationsDevicesSafesDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
