// Code generated by go-swagger; DO NOT EDIT.

package notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewNotificationsDevicesDeleteParams creates a new NotificationsDevicesDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewNotificationsDevicesDeleteParams() *NotificationsDevicesDeleteParams {
	return &NotificationsDevicesDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewNotificationsDevicesDeleteParamsWithTimeout creates a new NotificationsDevicesDeleteParams object
// with the ability to set a timeout on a request.
func NewNotificationsDevicesDeleteParamsWithTimeout(timeout time.Duration) *NotificationsDevicesDeleteParams {
	return &NotificationsDevicesDeleteParams{
		timeout: timeout,
	}
}

// NewNotificationsDevicesDeleteParamsWithContext creates a new NotificationsDevicesDeleteParams object
// with the ability to set a context for a request.
func NewNotificationsDevicesDeleteParamsWithContext(ctx context.Context) *NotificationsDevicesDeleteParams {
	return &NotificationsDevicesDeleteParams{
		Context: ctx,
	}
}

// NewNotificationsDevicesDeleteParamsWithHTTPClient creates a new NotificationsDevicesDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewNotificationsDevicesDeleteParamsWithHTTPClient(client *http.Client) *NotificationsDevicesDeleteParams {
	return &NotificationsDevicesDeleteParams{
		HTTPClient: client,
	}
}

/* NotificationsDevicesDeleteParams contains all the parameters to send to the API endpoint
   for the notifications devices delete operation.

   Typically these are written to a http.Request.
*/
type NotificationsDevicesDeleteParams struct {

	/* UUID.

	   A UUID string identifying this Firebase Device.

	   Format: uuid
	*/
	UUID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the notifications devices delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NotificationsDevicesDeleteParams) WithDefaults() *NotificationsDevicesDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the notifications devices delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *NotificationsDevicesDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the notifications devices delete params
func (o *NotificationsDevicesDeleteParams) WithTimeout(timeout time.Duration) *NotificationsDevicesDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the notifications devices delete params
func (o *NotificationsDevicesDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the notifications devices delete params
func (o *NotificationsDevicesDeleteParams) WithContext(ctx context.Context) *NotificationsDevicesDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the notifications devices delete params
func (o *NotificationsDevicesDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the notifications devices delete params
func (o *NotificationsDevicesDeleteParams) WithHTTPClient(client *http.Client) *NotificationsDevicesDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the notifications devices delete params
func (o *NotificationsDevicesDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUUID adds the uuid to the notifications devices delete params
func (o *NotificationsDevicesDeleteParams) WithUUID(uuid strfmt.UUID) *NotificationsDevicesDeleteParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the notifications devices delete params
func (o *NotificationsDevicesDeleteParams) SetUUID(uuid strfmt.UUID) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *NotificationsDevicesDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
