// Code generated by go-swagger; DO NOT EDIT.

package notifications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MoonSHRD/dao-tg/pkg/gnosis/models"
)

// NotificationsDevicesCreateReader is a Reader for the NotificationsDevicesCreate structure.
type NotificationsDevicesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NotificationsDevicesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewNotificationsDevicesCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNotificationsDevicesCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewNotificationsDevicesCreateOK creates a NotificationsDevicesCreateOK with default headers values
func NewNotificationsDevicesCreateOK() *NotificationsDevicesCreateOK {
	return &NotificationsDevicesCreateOK{}
}

/* NotificationsDevicesCreateOK describes a response with status code 200, with default header values.

NotificationsDevicesCreateOK notifications devices create o k
*/
type NotificationsDevicesCreateOK struct {
	Payload *models.FirebaseDeviceSerializerWithOwnersResponse
}

func (o *NotificationsDevicesCreateOK) Error() string {
	return fmt.Sprintf("[POST /notifications/devices/][%d] notificationsDevicesCreateOK  %+v", 200, o.Payload)
}
func (o *NotificationsDevicesCreateOK) GetPayload() *models.FirebaseDeviceSerializerWithOwnersResponse {
	return o.Payload
}

func (o *NotificationsDevicesCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FirebaseDeviceSerializerWithOwnersResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNotificationsDevicesCreateBadRequest creates a NotificationsDevicesCreateBadRequest with default headers values
func NewNotificationsDevicesCreateBadRequest() *NotificationsDevicesCreateBadRequest {
	return &NotificationsDevicesCreateBadRequest{}
}

/* NotificationsDevicesCreateBadRequest describes a response with status code 400, with default header values.

Invalid data
*/
type NotificationsDevicesCreateBadRequest struct {
}

func (o *NotificationsDevicesCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /notifications/devices/][%d] notificationsDevicesCreateBadRequest ", 400)
}

func (o *NotificationsDevicesCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
