// Code generated by go-swagger; DO NOT EDIT.

package data_decoder

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new data decoder API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for data decoder API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DataDecoderCreate(params *DataDecoderCreateParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DataDecoderCreateOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  DataDecoderCreate Returns decoded information using tx service internal ABI information given the tx
data as a `0x` prefixed hexadecimal string.
If address of the receiving contract is provided decoded data will be more accurate,
as in case of ABI collision service will know which ABI to use.
*/
func (a *Client) DataDecoderCreate(params *DataDecoderCreateParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DataDecoderCreateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDataDecoderCreateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "data-decoder_create",
		Method:             "POST",
		PathPattern:        "/data-decoder/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DataDecoderCreateReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DataDecoderCreateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for data-decoder_create: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
