// Code generated by go-swagger; DO NOT EDIT.

package data_decoder

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DataDecoderCreateReader is a Reader for the DataDecoderCreate structure.
type DataDecoderCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DataDecoderCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDataDecoderCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDataDecoderCreateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewDataDecoderCreateUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDataDecoderCreateOK creates a DataDecoderCreateOK with default headers values
func NewDataDecoderCreateOK() *DataDecoderCreateOK {
	return &DataDecoderCreateOK{}
}

/* DataDecoderCreateOK describes a response with status code 200, with default header values.

Decoded data
*/
type DataDecoderCreateOK struct {
}

func (o *DataDecoderCreateOK) Error() string {
	return fmt.Sprintf("[POST /data-decoder/][%d] dataDecoderCreateOK ", 200)
}

func (o *DataDecoderCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDataDecoderCreateNotFound creates a DataDecoderCreateNotFound with default headers values
func NewDataDecoderCreateNotFound() *DataDecoderCreateNotFound {
	return &DataDecoderCreateNotFound{}
}

/* DataDecoderCreateNotFound describes a response with status code 404, with default header values.

Cannot find function selector to decode data
*/
type DataDecoderCreateNotFound struct {
}

func (o *DataDecoderCreateNotFound) Error() string {
	return fmt.Sprintf("[POST /data-decoder/][%d] dataDecoderCreateNotFound ", 404)
}

func (o *DataDecoderCreateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDataDecoderCreateUnprocessableEntity creates a DataDecoderCreateUnprocessableEntity with default headers values
func NewDataDecoderCreateUnprocessableEntity() *DataDecoderCreateUnprocessableEntity {
	return &DataDecoderCreateUnprocessableEntity{}
}

/* DataDecoderCreateUnprocessableEntity describes a response with status code 422, with default header values.

Invalid data
*/
type DataDecoderCreateUnprocessableEntity struct {
}

func (o *DataDecoderCreateUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /data-decoder/][%d] dataDecoderCreateUnprocessableEntity ", 422)
}

func (o *DataDecoderCreateUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
