// Code generated by go-swagger; DO NOT EDIT.

package about

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AboutListReader is a Reader for the AboutList structure.
type AboutListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AboutListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAboutListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAboutListOK creates a AboutListOK with default headers values
func NewAboutListOK() *AboutListOK {
	return &AboutListOK{}
}

/* AboutListOK describes a response with status code 200, with default header values.

AboutListOK about list o k
*/
type AboutListOK struct {
}

func (o *AboutListOK) Error() string {
	return fmt.Sprintf("[GET /about/][%d] aboutListOK ", 200)
}

func (o *AboutListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
