// Code generated by go-swagger; DO NOT EDIT.

package about

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAboutListParams creates a new AboutListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAboutListParams() *AboutListParams {
	return &AboutListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAboutListParamsWithTimeout creates a new AboutListParams object
// with the ability to set a timeout on a request.
func NewAboutListParamsWithTimeout(timeout time.Duration) *AboutListParams {
	return &AboutListParams{
		timeout: timeout,
	}
}

// NewAboutListParamsWithContext creates a new AboutListParams object
// with the ability to set a context for a request.
func NewAboutListParamsWithContext(ctx context.Context) *AboutListParams {
	return &AboutListParams{
		Context: ctx,
	}
}

// NewAboutListParamsWithHTTPClient creates a new AboutListParams object
// with the ability to set a custom HTTPClient for a request.
func NewAboutListParamsWithHTTPClient(client *http.Client) *AboutListParams {
	return &AboutListParams{
		HTTPClient: client,
	}
}

/* AboutListParams contains all the parameters to send to the API endpoint
   for the about list operation.

   Typically these are written to a http.Request.
*/
type AboutListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the about list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AboutListParams) WithDefaults() *AboutListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the about list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AboutListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the about list params
func (o *AboutListParams) WithTimeout(timeout time.Duration) *AboutListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the about list params
func (o *AboutListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the about list params
func (o *AboutListParams) WithContext(ctx context.Context) *AboutListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the about list params
func (o *AboutListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the about list params
func (o *AboutListParams) WithHTTPClient(client *http.Client) *AboutListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the about list params
func (o *AboutListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *AboutListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
