// Code generated by go-swagger; DO NOT EDIT.

package about

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAboutMasterCopiesListParams creates a new AboutMasterCopiesListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAboutMasterCopiesListParams() *AboutMasterCopiesListParams {
	return &AboutMasterCopiesListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAboutMasterCopiesListParamsWithTimeout creates a new AboutMasterCopiesListParams object
// with the ability to set a timeout on a request.
func NewAboutMasterCopiesListParamsWithTimeout(timeout time.Duration) *AboutMasterCopiesListParams {
	return &AboutMasterCopiesListParams{
		timeout: timeout,
	}
}

// NewAboutMasterCopiesListParamsWithContext creates a new AboutMasterCopiesListParams object
// with the ability to set a context for a request.
func NewAboutMasterCopiesListParamsWithContext(ctx context.Context) *AboutMasterCopiesListParams {
	return &AboutMasterCopiesListParams{
		Context: ctx,
	}
}

// NewAboutMasterCopiesListParamsWithHTTPClient creates a new AboutMasterCopiesListParams object
// with the ability to set a custom HTTPClient for a request.
func NewAboutMasterCopiesListParamsWithHTTPClient(client *http.Client) *AboutMasterCopiesListParams {
	return &AboutMasterCopiesListParams{
		HTTPClient: client,
	}
}

/* AboutMasterCopiesListParams contains all the parameters to send to the API endpoint
   for the about master copies list operation.

   Typically these are written to a http.Request.
*/
type AboutMasterCopiesListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the about master copies list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AboutMasterCopiesListParams) WithDefaults() *AboutMasterCopiesListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the about master copies list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AboutMasterCopiesListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the about master copies list params
func (o *AboutMasterCopiesListParams) WithTimeout(timeout time.Duration) *AboutMasterCopiesListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the about master copies list params
func (o *AboutMasterCopiesListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the about master copies list params
func (o *AboutMasterCopiesListParams) WithContext(ctx context.Context) *AboutMasterCopiesListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the about master copies list params
func (o *AboutMasterCopiesListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the about master copies list params
func (o *AboutMasterCopiesListParams) WithHTTPClient(client *http.Client) *AboutMasterCopiesListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the about master copies list params
func (o *AboutMasterCopiesListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *AboutMasterCopiesListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
