// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// TransactionsReadReader is a Reader for the TransactionsRead structure.
type TransactionsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TransactionsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTransactionsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewTransactionsReadNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewTransactionsReadOK creates a TransactionsReadOK with default headers values
func NewTransactionsReadOK() *TransactionsReadOK {
	return &TransactionsReadOK{}
}

/* TransactionsReadOK describes a response with status code 200, with default header values.

Ok
*/
type TransactionsReadOK struct {
}

func (o *TransactionsReadOK) Error() string {
	return fmt.Sprintf("[GET /transactions/{safe_tx_hash}/][%d] transactionsReadOK ", 200)
}

func (o *TransactionsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewTransactionsReadNotFound creates a TransactionsReadNotFound with default headers values
func NewTransactionsReadNotFound() *TransactionsReadNotFound {
	return &TransactionsReadNotFound{}
}

/* TransactionsReadNotFound describes a response with status code 404, with default header values.

Not found
*/
type TransactionsReadNotFound struct {
}

func (o *TransactionsReadNotFound) Error() string {
	return fmt.Sprintf("[GET /transactions/{safe_tx_hash}/][%d] transactionsReadNotFound ", 404)
}

func (o *TransactionsReadNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
