// Code generated by go-swagger; DO NOT EDIT.

package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTransactionsReadParams creates a new TransactionsReadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTransactionsReadParams() *TransactionsReadParams {
	return &TransactionsReadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTransactionsReadParamsWithTimeout creates a new TransactionsReadParams object
// with the ability to set a timeout on a request.
func NewTransactionsReadParamsWithTimeout(timeout time.Duration) *TransactionsReadParams {
	return &TransactionsReadParams{
		timeout: timeout,
	}
}

// NewTransactionsReadParamsWithContext creates a new TransactionsReadParams object
// with the ability to set a context for a request.
func NewTransactionsReadParamsWithContext(ctx context.Context) *TransactionsReadParams {
	return &TransactionsReadParams{
		Context: ctx,
	}
}

// NewTransactionsReadParamsWithHTTPClient creates a new TransactionsReadParams object
// with the ability to set a custom HTTPClient for a request.
func NewTransactionsReadParamsWithHTTPClient(client *http.Client) *TransactionsReadParams {
	return &TransactionsReadParams{
		HTTPClient: client,
	}
}

/* TransactionsReadParams contains all the parameters to send to the API endpoint
   for the transactions read operation.

   Typically these are written to a http.Request.
*/
type TransactionsReadParams struct {

	// SafeTxHash.
	SafeTxHash string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the transactions read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TransactionsReadParams) WithDefaults() *TransactionsReadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the transactions read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TransactionsReadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the transactions read params
func (o *TransactionsReadParams) WithTimeout(timeout time.Duration) *TransactionsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the transactions read params
func (o *TransactionsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the transactions read params
func (o *TransactionsReadParams) WithContext(ctx context.Context) *TransactionsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the transactions read params
func (o *TransactionsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the transactions read params
func (o *TransactionsReadParams) WithHTTPClient(client *http.Client) *TransactionsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the transactions read params
func (o *TransactionsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSafeTxHash adds the safeTxHash to the transactions read params
func (o *TransactionsReadParams) WithSafeTxHash(safeTxHash string) *TransactionsReadParams {
	o.SetSafeTxHash(safeTxHash)
	return o
}

// SetSafeTxHash adds the safeTxHash to the transactions read params
func (o *TransactionsReadParams) SetSafeTxHash(safeTxHash string) {
	o.SafeTxHash = safeTxHash
}

// WriteToRequest writes these params to a swagger request
func (o *TransactionsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param safe_tx_hash
	if err := r.SetPathParam("safe_tx_hash", o.SafeTxHash); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
