// Code generated by go-swagger; DO NOT EDIT.

package multisig_transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMultisigTransactionsReadParams creates a new MultisigTransactionsReadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMultisigTransactionsReadParams() *MultisigTransactionsReadParams {
	return &MultisigTransactionsReadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMultisigTransactionsReadParamsWithTimeout creates a new MultisigTransactionsReadParams object
// with the ability to set a timeout on a request.
func NewMultisigTransactionsReadParamsWithTimeout(timeout time.Duration) *MultisigTransactionsReadParams {
	return &MultisigTransactionsReadParams{
		timeout: timeout,
	}
}

// NewMultisigTransactionsReadParamsWithContext creates a new MultisigTransactionsReadParams object
// with the ability to set a context for a request.
func NewMultisigTransactionsReadParamsWithContext(ctx context.Context) *MultisigTransactionsReadParams {
	return &MultisigTransactionsReadParams{
		Context: ctx,
	}
}

// NewMultisigTransactionsReadParamsWithHTTPClient creates a new MultisigTransactionsReadParams object
// with the ability to set a custom HTTPClient for a request.
func NewMultisigTransactionsReadParamsWithHTTPClient(client *http.Client) *MultisigTransactionsReadParams {
	return &MultisigTransactionsReadParams{
		HTTPClient: client,
	}
}

/* MultisigTransactionsReadParams contains all the parameters to send to the API endpoint
   for the multisig transactions read operation.

   Typically these are written to a http.Request.
*/
type MultisigTransactionsReadParams struct {

	// SafeTxHash.
	SafeTxHash string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the multisig transactions read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MultisigTransactionsReadParams) WithDefaults() *MultisigTransactionsReadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the multisig transactions read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MultisigTransactionsReadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the multisig transactions read params
func (o *MultisigTransactionsReadParams) WithTimeout(timeout time.Duration) *MultisigTransactionsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the multisig transactions read params
func (o *MultisigTransactionsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the multisig transactions read params
func (o *MultisigTransactionsReadParams) WithContext(ctx context.Context) *MultisigTransactionsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the multisig transactions read params
func (o *MultisigTransactionsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the multisig transactions read params
func (o *MultisigTransactionsReadParams) WithHTTPClient(client *http.Client) *MultisigTransactionsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the multisig transactions read params
func (o *MultisigTransactionsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSafeTxHash adds the safeTxHash to the multisig transactions read params
func (o *MultisigTransactionsReadParams) WithSafeTxHash(safeTxHash string) *MultisigTransactionsReadParams {
	o.SetSafeTxHash(safeTxHash)
	return o
}

// SetSafeTxHash adds the safeTxHash to the multisig transactions read params
func (o *MultisigTransactionsReadParams) SetSafeTxHash(safeTxHash string) {
	o.SafeTxHash = safeTxHash
}

// WriteToRequest writes these params to a swagger request
func (o *MultisigTransactionsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param safe_tx_hash
	if err := r.SetPathParam("safe_tx_hash", o.SafeTxHash); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
