// Code generated by go-swagger; DO NOT EDIT.

package multisig_transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/MoonSHRD/dao-tg/pkg/gnosis/models"
)

// NewMultisigTransactionsConfirmationsCreateParams creates a new MultisigTransactionsConfirmationsCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMultisigTransactionsConfirmationsCreateParams() *MultisigTransactionsConfirmationsCreateParams {
	return &MultisigTransactionsConfirmationsCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMultisigTransactionsConfirmationsCreateParamsWithTimeout creates a new MultisigTransactionsConfirmationsCreateParams object
// with the ability to set a timeout on a request.
func NewMultisigTransactionsConfirmationsCreateParamsWithTimeout(timeout time.Duration) *MultisigTransactionsConfirmationsCreateParams {
	return &MultisigTransactionsConfirmationsCreateParams{
		timeout: timeout,
	}
}

// NewMultisigTransactionsConfirmationsCreateParamsWithContext creates a new MultisigTransactionsConfirmationsCreateParams object
// with the ability to set a context for a request.
func NewMultisigTransactionsConfirmationsCreateParamsWithContext(ctx context.Context) *MultisigTransactionsConfirmationsCreateParams {
	return &MultisigTransactionsConfirmationsCreateParams{
		Context: ctx,
	}
}

// NewMultisigTransactionsConfirmationsCreateParamsWithHTTPClient creates a new MultisigTransactionsConfirmationsCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewMultisigTransactionsConfirmationsCreateParamsWithHTTPClient(client *http.Client) *MultisigTransactionsConfirmationsCreateParams {
	return &MultisigTransactionsConfirmationsCreateParams{
		HTTPClient: client,
	}
}

/* MultisigTransactionsConfirmationsCreateParams contains all the parameters to send to the API endpoint
   for the multisig transactions confirmations create operation.

   Typically these are written to a http.Request.
*/
type MultisigTransactionsConfirmationsCreateParams struct {

	// Data.
	Data *models.SafeMultisigConfirmation

	// SafeTxHash.
	SafeTxHash string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the multisig transactions confirmations create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MultisigTransactionsConfirmationsCreateParams) WithDefaults() *MultisigTransactionsConfirmationsCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the multisig transactions confirmations create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MultisigTransactionsConfirmationsCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the multisig transactions confirmations create params
func (o *MultisigTransactionsConfirmationsCreateParams) WithTimeout(timeout time.Duration) *MultisigTransactionsConfirmationsCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the multisig transactions confirmations create params
func (o *MultisigTransactionsConfirmationsCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the multisig transactions confirmations create params
func (o *MultisigTransactionsConfirmationsCreateParams) WithContext(ctx context.Context) *MultisigTransactionsConfirmationsCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the multisig transactions confirmations create params
func (o *MultisigTransactionsConfirmationsCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the multisig transactions confirmations create params
func (o *MultisigTransactionsConfirmationsCreateParams) WithHTTPClient(client *http.Client) *MultisigTransactionsConfirmationsCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the multisig transactions confirmations create params
func (o *MultisigTransactionsConfirmationsCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the multisig transactions confirmations create params
func (o *MultisigTransactionsConfirmationsCreateParams) WithData(data *models.SafeMultisigConfirmation) *MultisigTransactionsConfirmationsCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the multisig transactions confirmations create params
func (o *MultisigTransactionsConfirmationsCreateParams) SetData(data *models.SafeMultisigConfirmation) {
	o.Data = data
}

// WithSafeTxHash adds the safeTxHash to the multisig transactions confirmations create params
func (o *MultisigTransactionsConfirmationsCreateParams) WithSafeTxHash(safeTxHash string) *MultisigTransactionsConfirmationsCreateParams {
	o.SetSafeTxHash(safeTxHash)
	return o
}

// SetSafeTxHash adds the safeTxHash to the multisig transactions confirmations create params
func (o *MultisigTransactionsConfirmationsCreateParams) SetSafeTxHash(safeTxHash string) {
	o.SafeTxHash = safeTxHash
}

// WriteToRequest writes these params to a swagger request
func (o *MultisigTransactionsConfirmationsCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param safe_tx_hash
	if err := r.SetPathParam("safe_tx_hash", o.SafeTxHash); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
