// Code generated by go-swagger; DO NOT EDIT.

package multisig_transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/MoonSHRD/dao-tg/pkg/gnosis/models"
)

// MultisigTransactionsReadReader is a Reader for the MultisigTransactionsRead structure.
type MultisigTransactionsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MultisigTransactionsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMultisigTransactionsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewMultisigTransactionsReadOK creates a MultisigTransactionsReadOK with default headers values
func NewMultisigTransactionsReadOK() *MultisigTransactionsReadOK {
	return &MultisigTransactionsReadOK{}
}

/* MultisigTransactionsReadOK describes a response with status code 200, with default header values.

MultisigTransactionsReadOK multisig transactions read o k
*/
type MultisigTransactionsReadOK struct {
	Payload *models.SafeMultisigTransactionResponse
}

func (o *MultisigTransactionsReadOK) Error() string {
	return fmt.Sprintf("[GET /multisig-transactions/{safe_tx_hash}/][%d] multisigTransactionsReadOK  %+v", 200, o.Payload)
}
func (o *MultisigTransactionsReadOK) GetPayload() *models.SafeMultisigTransactionResponse {
	return o.Payload
}

func (o *MultisigTransactionsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SafeMultisigTransactionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
