// Code generated by go-swagger; DO NOT EDIT.

package multisig_transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// MultisigTransactionsConfirmationsCreateReader is a Reader for the MultisigTransactionsConfirmationsCreate structure.
type MultisigTransactionsConfirmationsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MultisigTransactionsConfirmationsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewMultisigTransactionsConfirmationsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewMultisigTransactionsConfirmationsCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewMultisigTransactionsConfirmationsCreateUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewMultisigTransactionsConfirmationsCreateCreated creates a MultisigTransactionsConfirmationsCreateCreated with default headers values
func NewMultisigTransactionsConfirmationsCreateCreated() *MultisigTransactionsConfirmationsCreateCreated {
	return &MultisigTransactionsConfirmationsCreateCreated{}
}

/* MultisigTransactionsConfirmationsCreateCreated describes a response with status code 201, with default header values.

Created
*/
type MultisigTransactionsConfirmationsCreateCreated struct {
}

func (o *MultisigTransactionsConfirmationsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /multisig-transactions/{safe_tx_hash}/confirmations/][%d] multisigTransactionsConfirmationsCreateCreated ", 201)
}

func (o *MultisigTransactionsConfirmationsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewMultisigTransactionsConfirmationsCreateBadRequest creates a MultisigTransactionsConfirmationsCreateBadRequest with default headers values
func NewMultisigTransactionsConfirmationsCreateBadRequest() *MultisigTransactionsConfirmationsCreateBadRequest {
	return &MultisigTransactionsConfirmationsCreateBadRequest{}
}

/* MultisigTransactionsConfirmationsCreateBadRequest describes a response with status code 400, with default header values.

Malformed data
*/
type MultisigTransactionsConfirmationsCreateBadRequest struct {
}

func (o *MultisigTransactionsConfirmationsCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /multisig-transactions/{safe_tx_hash}/confirmations/][%d] multisigTransactionsConfirmationsCreateBadRequest ", 400)
}

func (o *MultisigTransactionsConfirmationsCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewMultisigTransactionsConfirmationsCreateUnprocessableEntity creates a MultisigTransactionsConfirmationsCreateUnprocessableEntity with default headers values
func NewMultisigTransactionsConfirmationsCreateUnprocessableEntity() *MultisigTransactionsConfirmationsCreateUnprocessableEntity {
	return &MultisigTransactionsConfirmationsCreateUnprocessableEntity{}
}

/* MultisigTransactionsConfirmationsCreateUnprocessableEntity describes a response with status code 422, with default header values.

Error processing data
*/
type MultisigTransactionsConfirmationsCreateUnprocessableEntity struct {
}

func (o *MultisigTransactionsConfirmationsCreateUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /multisig-transactions/{safe_tx_hash}/confirmations/][%d] multisigTransactionsConfirmationsCreateUnprocessableEntity ", 422)
}

func (o *MultisigTransactionsConfirmationsCreateUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
